'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'ku' | 'en' | 'kmr';

interface LanguageContextType {
  currentLanguage: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: 'rtl' | 'ltr';
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation data
const translations = {
  ku: {
    'site.title': 'کتابخانەی کوردی',
    'site.description': 'باشترین فرۆشگای ئۆنلاین بۆ کتابەکانی کوردی',
    'nav.home': 'سەرەتا',
    'nav.categories': 'پۆلەکان',
    'nav.books': 'کتابەکان',
    'nav.authors': 'نووسەران',
    'nav.arts': 'هونەر و کلتور',
    'nav.about': 'دەربارە',
    'nav.contact': 'پەیوەندی',
    'nav.cart': 'سەبەتە',
    'nav.wishlist': 'لیستی خوازراوی',
    'nav.profile': 'پرۆفایل',
    'nav.menu': 'مینو',
    'nav.language': 'زمان',
    'nav.search': 'گەڕان',
    'nav.login': 'چوونە ژوورەوە',
    'nav.register': 'تۆمارکردن',
    'header.orderStatus': 'دۆخی داواکاری',
    'header.account': 'هەژمار',
    'common.search': 'گەڕان',
    'app.name': 'کتابخانەی کوردی',
    'home.welcome': 'بەخێربێیت بۆ کتابخانەی کوردی',
    'home.subtitle': 'باشترین فرۆشگای ئۆنلاین بۆ کتابەکانی کوردی',
    'home.featured': 'کتابە تایبەتەکان',
    'home.featuredSubtitle': 'پێشنیارەکانمان بۆ تۆ',
    'home.bestsellers': 'باشترین فرۆشراوەکان',
    'home.bestsellersSubtitle': 'بەناوبانگترین کتێبەکان لای کڕیاران',
    'home.newReleases': 'کتابە نوێکان',
    'home.newReleasesSubtitle': 'نوێترین بڵاوکراوەکان ببینە',
    'home.newReleasesDesc': 'کۆمەڵێک لە نوێترین و باشترین کتێبە کوردییەکان',
    'homepage.welcome': 'بەخێربێیت بۆ کتابخانەی کوردی',
    'homepage.subtitle': 'هەزاران کتێب بدۆزەرەوە',
    'homepage.inspiration': 'بخوێنە، فێربە، گەشە بکە',
    'homepage.newReleasesSubtitle': 'تازە بڵاوکراوەتەوە',
    'homepage.newReleasesDesc': 'نوێترین کتێبەکان ببینە لە کۆکراوەکەمان',
    'hero.searchPlaceholder': 'گەڕان بۆ کتێب، نووسەر...',
    'newsletter.title': 'بەشداری لە بازنەی ئەدەبیمان بکە',
    'newsletter.subtitle': 'نوێترین هەواڵەکان، کتێبە نوێکان و ئۆفەرە تایبەتەکان ڕاستەوخۆ وەربگرە.',
    'newsletter.placeholder': 'ئیمەیڵەکەت بنووسە',
    'newsletter.button': 'بەشداربوون',
    'footer.description': 'باشترین شوێن بۆ ئەدەبیات، کلتوور و مێژووی کوردی. بەستنەوەی خوێنەران بە دەوڵەمەندی میراتەکەمان لە ڕێگەی هەڵبژاردەیەکی ورد لە کتێبەکان.',
    'footer.newsletterDescription': 'نوێترین هەواڵەکان، کتێبە نوێکان و ئۆفەرە تایبەتەکان ڕاستەوخۆ وەربگرە.',
    'footer.emailPlaceholder': 'ئیمەیڵەکەت بنووسە',
    'ads.adSpace': 'شوێنی ریکلام',
    'common.by': 'نووسینی',
    'offers.limitedTime': 'کاتی دیاریکراو',
    'home.viewAll': 'بینینی هەموو',
    'hero.badge': 'کۆمەڵەی نوێ ٢٠٢٥',
    'book.price': 'نرخ',
    'book.by': 'لەلایەن:',
    'book.author': 'نووسەر',
    'book.publisher': 'ناشر:',
    'book.reviews': 'نرخاندن',
    'book.quantity': 'بڕ:',
    'book.pages': 'لاپەڕە:',
    'book.language': 'زمان:',
    'book.publishDate': 'بەرواری بڵاوکردنەوە:',
    'book.description': 'وەسف',
    'book.moreInfo': 'زانیاری زیاتر',
    'book.tags': 'تاگەکان:',
    'book.technicalInfo': 'زانیاری تەکنیکی',
    'book.category': 'پۆل',
    'book.relatedBooks': 'کتابە هاوشێوەکان',
    'book.addToCart': 'زیادکردن بۆ سەبەتە',
    'book.buyNow': 'ئێستا بیکڕە',
    'book.inStock': 'بەردەستە',
    'book.outOfStock': 'ناوبەردەست',
    'book.customersAlsoBought': 'کڕیارانی تر ئەمشیان کڕیوە',
    'book.information': 'زانیاری دەربارەی کتێب',
    'book.giftTitle': 'ئەم کتێبە بکە بە دیاری',
    'book.giftSubtitle': 'زۆر ئاسانە',
    'book.interestingTopics': 'شاید ئەم بابەتانەش جالب بن',
    'book.fullName': 'ناوی تەواو',
    'book.binding': 'بەرگ',
    'book.releaseDate': 'بەرواری بڵاوکردنەوە',
    'book.ean': 'EAN',
    'book.isbn': 'ISBN',
    'book.libristoCode': 'کۆدی لیبریستۆ',
    'book.weight': 'کێش',
    'book.dimensions': 'قەبارە',
    'book.giftStep1': 'کتێبەکە بخە ناو سەبەتەکەت و "ناردن وەک دیاری" هەڵبژێرە',
    'book.giftStep2': 'ئێمە دەستبەجێ پسوڵەیەکت بۆ دەنێرین',
    'book.giftStep3': 'کتێبەکە بۆ ناونیشانی وەرگر دەنێردرێت',
    'book.deliveryPromise': 'گەیاندن پێش سەری ساڵ',
    'book.externalStock': 'کۆگای دەرەکی',
    'book.shippingTime': 'گەیاندن لە ٤-٧ ڕۆژدا',
    'book.returnPolicy': 'مافی گەڕاندنەوەی ٣٠ ڕۆژ',
    'book.fullDescription': 'وەسفی تەواو',
    'book.inclVAT': 'بە باجەوە',
    'cart.title': 'سەبەتەی کڕین',
    'cart.empty': 'سەبەتەکەت بەتاڵە',
    'cart.total': 'کۆی گشتی',
    'cart.checkout': 'چوونە سەر سندوق',
    'cart.youMightAlsoLike': 'کتابەکانی تر کە ڕەنگە حەزت لێبێت',
    'search.title': 'گەڕان',
    'search.placeholder': 'ناوی کتاب، نووسەر یان پۆل بنووسە...',
    'search.noResults': 'هیچ کتابێک نەدۆزرایەوە',
    'search.filters': 'فیلتەرەکان',
    'search.sortBy': 'ریزکردن بەپێی:',
    'search.newest': 'نوێترین',
    'search.oldest': 'کۆنترین',
    'search.nameAZ': 'ناو (ئ - ی)',
    'search.nameZA': 'ناو (ی - ئ)',
    'search.priceLowHigh': 'نرخ نزم بۆ بەرز',
    'search.priceHighLow': 'نرخ بەرز بۆ نزم',
    'search.mostPopular': 'باشترین',
    'search.allCategories': 'هەموو پۆلەکان',
    'search.priceRange': 'ناوچەی نرخ',
    'search.minPrice': 'کەمترین نرخ',
    'search.maxPrice': 'زۆرترین نرخ',
    'search.applyFilter': 'بەکارهێنان',
    'search.showAll': 'پیشاندانی هەموو',
    'search.resultsFound': 'ئەنجام دۆزرایەوە',
    'search.hideFilters': 'شاردنەوەی فیلتەرەکان',
    'search.resetAll': 'پاککردنەوەی هەموو',
    'search.noResultsFor': 'هیچ کتێبێک نەدۆزرایەوە بۆ',
    'search.clearSearch': 'پاککردنەوەی گەڕان',
    'search.loading': 'گەڕان...',
    'authors.title': 'نووسەران',
    'authors.biography': 'ژیاننامە',
    'authors.viewProfile': 'بینینی پرۆفایڵ',
    'auth.login': 'ژوورەوە',
    'auth.register': 'خۆناوکردن',
    'auth.email': 'ئیمێڵ',
    'auth.password': 'زِروشە',
    'auth.confirmPassword': 'دووبارە زِروشە',
    'auth.name': 'ناو',
    'auth.forgotPassword': 'زِروشەت لەبیرچووە؟',
    'auth.noAccount': 'هەژمارت نیە؟',
    'auth.haveAccount': 'پێشتر خۆت تۆمار کردووە؟',
    'auth.signIn': 'چوونە ژوورەوە',
    'auth.signUp': 'خۆت تۆمار بکە',
    'auth.rememberMe': 'لەبیرم بکه',
    'auth.quickTest': 'تاقیکردنی خێرا',
    'auth.forTesting': 'بۆ تاقیکردنەوە:',
    'auth.emailLabel': 'ئیمەیل:',
    'auth.passwordLabel': 'پاسۆرد:',
    'auth.error.invalidCredentials': 'ئیمەیل یان پاسۆرد هەڵەیە',
    'auth.error.emailUsed': 'ئەم ئیمەیلە پێشتر بەکارهاتووە',
    'auth.createAccount': 'هەژمارێکی نوێ دروست بکە',
    'auth.orLogin': 'یان بچۆ ژوورەوە',
    'auth.firstName': 'ناوی یەکەم',
    'auth.lastName': 'ناوی دووەم',
    'auth.phone': 'ژمارەی تەلەفۆن',
    'auth.optional': '(ئیختیاری)',
    'auth.chooseStrongPassword': 'پاسۆردێکی بەهێز هەڵبژێرە',
    'auth.minChars': 'لانیکەم ٦ پیت دەبێت',
    'auth.creatingAccount': 'هەژمار دروست بکە',
    'auth.termsAgreement': 'هەژمار دروستکردن واتە ڕازیبوونە بە',
    'auth.terms': 'مەرجەکان',
    'auth.privacyPolicy': 'سیاسەتی تایبەتێتی',
    'auth.and': 'و',
    'book.inCart': 'سەبەت',
    'book.notInCart': 'نییە',
    'profile.dashboard': 'دەشبۆرد',
    'profile.orders': 'داواکاریەکان',
    'profile.wishlist': 'لیستی ویستەکان',
    'profile.addresses': 'ناونیشانەکان',
    'profile.accountDetails': 'وردەکاری هەژمار',
    'profile.logout': 'دەرچوون',
    'profile.personalInfo': 'زانیاری کەسایەتی',
    'profile.updateInfo': 'نوێکردنەوەی زانیاریەکان',
    'profile.save': 'پاشەکەوتکردن',
    'profile.changePassword': 'گۆڕینی زِروشە',
    'profile.orderHistory': 'مێژووی داواکاریەکان',
    'profile.noOrders': 'هیچ داواکارییەکت نیە',
    'profile.orderDetails': 'وردەکاری داواکاری',
    'profile.recentOrders': 'دوایین داواکاریەکان',
    'profile.settings': 'مîheng',
    'profile.edit': 'بگوهرینه',
    'profile.cancel': 'پاشگەزبوونه‌وه',
    'profile.firstName': 'ناو',
    'profile.lastName': 'پاشناو',
    'profile.email': 'E-name',
    'profile.phone': 'Hejmara Telefonê',
    'profile.address': 'Navnîşan',
    'profile.city': 'Bajar',
    'profile.zipCode': 'Koda Postayê',
    'profile.loading': 'Profîl tê barkirin...',
    'status.available': 'بەردەستە',
    'status.unavailable': 'ناوبەردەست',
    'status.outOfStock': 'لە کۆمەڵ چووە',
    'form.required': 'وایە',
    'form.invalidEmail': 'ئیمێڵەکە دروست نیە',
    'form.passwordsDontMatch': 'زِروشەکان یەکنین',
    'form.passwordTooShort': 'زِروشە باید لای کەمی ٦ نووسە بێت',
    'common.loading': 'چاوەڕێ بکە...',
    'common.pleaseWait': 'چاوەڕێ بکە...',
    'common.error': 'هەڵەیەک ڕوویدا',
    'common.success': 'سەرکەوتوو بوو',
    'buttons.viewAll': 'بینینی هەموو',
    'buttons.viewAllShort': 'هەمووی',
    'buttons.readMore': 'زیاتر بخوێنەرەوە',
    'buttons.addToCart': 'زیادکردن بۆ سەبەتە',
    'buttons.buyNow': 'ئێستا بیکڕە',
    'buttons.buy': 'کڕین',
    'buttons.save': 'پاشکەوتکردن',
    'buttons.cancel': 'پاشگەزبوونەوە',
    'buttons.edit': 'دەستکاری',
    'buttons.delete': 'سڕینەوە',
    'buttons.confirm': 'پەسەندکردن',
    'buttons.viewDetails': 'بینینی وردەکاری',
    'categories.literature': 'ئەدەبیات',
    'categories.poetry': 'شیعر',
    'categories.history': 'مێژوو',
    'categories.children': 'منداڵان',
    'categories.education': 'پەروەردە',
    'categories.science': 'زانست',
    'categories.religion': 'ئایین',
    'categories.biography': 'ژیاننامە',
    'categories.philosophy': 'فەلسەفە',
    'categories.politics': 'سیاسەت',
    'categories.culture': 'کلتوور',
    'footer.aboutUs': 'دەربارەی ئێمە',
    'footer.contactInfo': 'زانیاری پەیوەندی',
    'footer.followUs': 'شوێنمان بکەوە',
    'footer.copyright': 'مافی چاپ کتابخانەی کوردی. هەموو مافەکان پارێزراون.',
    'sections.featuredBooks': 'کتابە تایبەتەکان',
    'sections.bestSellers': 'باشترین فرۆشراوەکان',
    'sections.newReleases': 'کتابە نوێکان',
    'sections.specialOffers': 'پێشکەشە تایبەتەکان',
    'sections.statistics': 'ئامارەکان',
    'offers.discount': 'داشکاندنی تا ٥٠٪ لەسەر کتابە هەڵبژاردەکان',
    'offers.viewOffers': 'بینینی پێشکەشەکان',
    'stats.books': 'کتاب',
    'stats.authors': 'نووسەر',
    'stats.publishers': 'ناشر',
    // Admin translations
    'admin.login': 'چوونە ژوورەوەی بەڕێوەبەر',
    'admin.username': 'ناوی بەکارهێنەر',
    'admin.password': 'وشەی نهێنی',
    'admin.enterUsername': 'ناوی بەکارهێنەر',
    'admin.enterPassword': 'وشەی نهێنی',
    'admin.loginButton': 'چوونە ژوورەوە',
    'admin.loggingIn': 'چاوەڕوان بە...',
    'admin.invalidCredentials': 'ناوی بەکارهێنەر یان وشەی نهێنی هەڵەیە',
    'admin.accessPanel': 'بۆ دەستڕاگەیشتن بە پانێڵی بەڕێوەبەر',
    'admin.demoCredentials': 'زانیاریەکانی تاقیکردنەوە:',
    'admin.panel': 'پانێڵی بەڕێوەبەر',
    'admin.welcome': 'بەخێربێیت بەڕێوەبەر',
    'admin.logout': 'دەرچوون',
    'admin.dashboard': 'داشبۆرد',
    'admin.manageBooks': 'بەڕێوەبردنی کتابەکان',
    'admin.manageAuthors': 'بەڕێوەبردنی نووسەران',
    'admin.addBook': 'کتابی نوێ',
    'admin.addAuthor': 'نووسەری نوێ',
    'admin.addNewBook': 'کتابی نوێ زیاد بکە',
    'admin.addNewAuthor': 'نووسەری نوێ زیاد بکە',
    'admin.title': 'ناونیشان',
    'admin.author': 'نووسەر',
    'admin.publisher': 'چاپخانە',
    'admin.price': 'نرخ (یۆرۆ)',
    'admin.description': 'وهسف',
    'admin.nameKurdish': 'ناو (کوردی)',
    'admin.nameLatin': 'ناو (لاتینی)',
    'admin.birthYear': 'ساڵی لەدایکبوون',
    'admin.deathYear': 'ساڵی مردن (ئاپشناڵ)',
    'admin.biographyKurdish': 'بیۆگرافی (کوردی)',
    'admin.totalBooks': 'کتابەکان',
    'admin.totalAuthors': 'نووسەران',
    'admin.totalReviews': 'نرخاندنەکان',
    'admin.avgRating': 'ڕێژەی نرخاندن',
    'admin.recentActivity': 'چالاکیە تازەکان',
    'admin.bookAdded': 'کتاب زیادکرا!',
    'admin.authorAdded': 'نووسەر زیادکرا!',
    'admin.actions': 'کردارەکان',
    'admin.rating': 'نرخاندن',
    'admin.books': 'کتاب',
    'stats.customers': 'کڕیار دڵخۆش',
    'description.categories': 'کتابەکان بە پێی بابەت و پۆل دابەش کراون',
    'footer.aboutTitle': 'دەربارەی ئێمە',
    'footer.aboutDescription': 'کتابخانەی کوردی باشترین فرۆشگای ئۆنلاینە بۆ کتابەکانی کوردی',
    'footer.quickLinks': 'بەستەر خێراکان',
    'footer.customerService': 'خزمەتگوزاری کڕیار',
    'footer.contact': 'پەیوەندی',
    'footer.newsletter': 'نیوزلێتەر',
    'footer.subscribe': 'نووسین',
    'auth.profile': 'پرۆفایل',
    'auth.orders': 'داواکاریەکان',
    'auth.favorites': 'دڵخوازەکان',
    'auth.logout': 'چوونەدەرەوە',
    'cart.itemCount': 'کۆی کتابەکان:',
    'cart.subtotal': 'کۆی نرخ:',
    'cart.shipping': 'گەیاندن:',
    'cart.shippingFree': 'خۆڕایی',
    'cart.continueShopping': 'دەوامی کڕین',
    'cart.emptyMessage': 'هیچ کتابێکت نەخستووەتە ناو سەبەتەکەت',
    'cart.clearCart': 'پاککردنەوەی سەبەتە',
    'cart.orderSummary': 'کورتەی سفارش',
    'cart.freeShipping': 'گەیاندنی خۆڕایی',
    'cart.returns': 'گەڕاندنەوەی ٧ ڕۆژ',
    'cart.buyerProtection': 'پاراستنی کڕیار',
    'cart.remove': 'سڕینەوە',
    'footer.shipping': 'گەیاندن',
    'footer.returns': 'گەڕاندنەوە',
    'footer.faq': 'پرسیارە دووبارەکان',
    'footer.help': 'یارمەتی',
    'footer.privacy': 'سیاسەتی تایبەتێتی',
    'footer.terms': 'مەرجەکانی بەکارهێنان',
    'footer.cookies': 'سیاسەتی کوکیز',
    'books.subtitle': 'گەڕان لە کتابە کوردییەکاندا',
    'books.category': 'پۆل',
    'books.search': 'گەڕان',
    'books.searchPlaceholder': 'گەڕان بە ناو یان نووسەر...',
    'books.sortBy': 'ڕیزکردن بە',
    'books.sortName': 'ناو',
    'books.sortPrice': 'نرخ',
    'books.sortRating': 'هەڵسەنگاندن',
    'books.sortYear': 'ساڵ',
    'books.found': 'دۆزرایەوە:',
    'books.noResults': 'هیچ کتابێک نەدۆزرایەوە',
    'books.noResultsMessage': 'تکایە گەڕانەکەت گۆڕین یان پالاوتنی جیاواز هەڵبژێرە',
    'books.inStockOnly': 'تەنها بەردەستەکان',
    'books.publishers': 'بڵاوکراوەکان',
    'books.all': 'هەموو',
    'books.authors': 'نووسەران',
    'books.searchPlaceholderLong': 'گەڕان بە ناونیشان، نووسەر، ISBN...',
    'books.results': 'ئەنجام',
    'books.sortBestselling': 'پڕفرۆشترین',
    'books.sortNewest': 'نوێترین',
    'books.sortPriceLowHigh': 'نرخ: کەم بۆ زۆر',
    'books.sortPriceHighLow': 'نرخ: زۆر بۆ کەم',
    'authors.subtitle': 'ناسین ببە بە نووسەرە بەناوبانگەکانی کوردی',
    'authors.search': 'گەڕان لە نووسەراندا...',
    'authors.sortBy': 'ڕیزبەندی',
    'authors.sortName': 'ناو',
    'authors.sortBooks': 'کتابەکان',
    'authors.sortYear': 'ساڵی لەدایکبوون',
    'authors.found': 'نووسەر دۆزرایەوە',
    'authors.birthYear': 'ساڵی لەدایکبوون:',
    'authors.nationality': 'نەتەوەیی:',
    'authors.noBooks': 'هیچ کتابێک نییە',
    'authors.noAuthorsFound': 'هیچ نووسەرێک نەدۆزرایەوە',
    'authors.popularAuthors': 'نووسەرە بەناوبانگەکان',
    'authors.clearSearch': 'پاککردنەوەی گەڕان',
    'authors.noAuthorsMessage': 'تکایە پەیوەندی جیاواز بەکار بهێنە',
    'authors.book': 'کتاب',
    'authors.books': 'کتاب',
    'authors.moreBooks': 'کتابی تر',
    'authors.literaryFigures': 'کەسایەتییە ئەدەبییەکان',
    'authors.bibliography': 'کتێبنامە',
    'authors.born': 'لەدایکبووی',
    'authors.noBooksAvailable': 'هیچ کتێبێک لەم کاتەدا بەردەست نییە',
    'category.empty': 'ئەم پۆلە لە ئێستادا بەتاڵە',
    'status.bestseller': 'باشترین فرۆشراو',
    'status.featured': 'تایبەت',
    'status.newRelease': 'نوێ',
    'status.sale': 'داشکاندن',
    'status.limited': 'سنووردار',
    'categories.all': 'هەموو پۆلەکان',
    'wishlist.title': 'لیستی دڵخواز',
    'wishlist.items': 'کتێب',
    'wishlist.continueShopping': 'زیاتر بگەڕێ',
    'wishlist.empty': 'لیستی دڵخوازت بەتاڵە',
    'wishlist.emptyMessage': 'هیچ کتێبێکت زیاد نەکردووە بۆ لیستی دڵخواز. کتێبەکان بگەڕێ و ئەوانەی بەدڵتە زیادیان بکە.',
    'wishlist.browseBooks': 'گەڕان بۆ کتێب',
    'wishlist.addToCart': 'زیادکردن بۆ سەبەتە',
    'wishlist.remove': 'لابردن',
    'checkout.information': 'زانیاری',
    'checkout.shipping': 'گەیاندن',
    'checkout.payment': 'پارەدان',
    'checkout.contactInfo': 'زانیاری پەیوەندی',
    'checkout.shippingAddress': 'ناونیشانی گەیاندن',
    'checkout.paymentMethod': 'شێوازی پارەدان',
    'checkout.orderPlaced': 'داواکارییەکەت وەرگیرا',
    'checkout.orderId': 'ژمارەی داواکاری',
    'checkout.thankYou': 'سوپاس بۆ کڕینەکەت. ئیمەیڵێکی پشتڕاستکردنەوەت بۆ دەنێرین.',
    'checkout.returnHome': 'گەڕانەوە بۆ ماڵەوە',
    'checkout.viewOrders': 'بینینی داواکارییەکان',
    'checkout.back': 'گەڕانەوە',
    'checkout.nextStep': 'دواتر',
    'checkout.placeOrder': 'تەواوکردنی داواکاری',
    'checkout.processing': 'جێبەجێکردن...',
    'checkout.creditCard': 'کارتی بانکی',
    'checkout.cashOnDelivery': 'پارەدان لە کاتی گەیاندن',
    'checkout.orderSummary': 'پوختەی داواکاری',
    'checkout.subtotal': 'کۆی گشتی کاڵاکان',
    'checkout.total': 'کۆی گشتی',
    'checkout.free': 'بەخۆڕایی',
    'checkout.qty': 'بڕ',
    'contact.title': 'پەیوەندیمان پێوە بکەن',
    'contact.subtitle': 'خۆشحاڵ دەبین گوێبیستی ڕای ئێوە بین. لێرەوە دەتوانن پەیوەندیمان پێوە بکەن.',
    'contact.form.name': 'ناوی تەواو',
    'contact.form.email': 'ئیمەیڵ',
    'contact.form.subject': 'بابەت',
    'contact.form.message': 'نامە',
    'contact.form.submit': 'ناردنی نامە',
    'contact.form.submitting': 'لە ناردندایە...',
    'contact.form.success': 'نامەکەت بە سەرکەوتوویی نێردرا! بەزوویی وەڵامت دەدەینەوە.',
    'contact.form.error': 'هەڵەیەک ڕوویدا. تکایە دووبارە هەوڵ بدەرەوە.',
    'contact.info.title': 'زانیاری پەیوەندی',
    'contact.info.email': 'info@kurdbook.com',
    'contact.info.phone': '+49 123 456 789',
    'contact.info.address': 'بەرلین، ئەڵمانیا',
    'contact.info.hours': 'دووشەممە - هەینی: ٩:٠٠ بەیانی - ٦:٠٠ ئێوارە',
    'contact.faq.title': 'پرسیارە باوەکان',
    'contact.faq.q1': 'ئایا گەیاندنتان بۆ دەرەوەی وڵات هەیە؟',
    'contact.faq.a1': 'بەڵێ، ئێمە بۆ زۆربەی وڵاتانی ئەوروپا و جیهان گەیاندنمان هەیە.',
    'contact.faq.q2': 'گەیاندن چەند کاتی پێ دەچێت؟',
    'contact.faq.a2': 'بەزۆری ٣-٥ ڕۆژی کارکردن لە ناو ئەوروپادا.',
    'contact.faq.q3': 'ئایا دەتوانم کتێبێک بگەڕێنمەوە؟',
    'contact.faq.a3': 'بەڵێ، لە ماوەی ١٤ ڕۆژدا دوای وەرگرتنی، ئەگەر کتێبەکە وەک خۆی مابێتەوە.',
    'about.title': 'زیاتر لە کتێبفرۆشییەک؛ لانەیەک بۆ کولتوور و هیوا',
    'about.subtitle': 'ئێمە کێین و بۆچی لێرەین؟',
    'about.intro': 'لە دڵی ئەوروپادا، کیلۆمەترها دوور لە چیاکانی نیشتمان، هەستمان بە بۆشاییەکی گەورە کرد. دەستگەیشتن بە کتێبی کوردی، کە گەنجینەی زمان و ناسنامەمانە، بۆ زۆرێک لە ئێمە لە تاراوگە ئەستەم یان مەحاڵ بوو. کورد بووک لەدایک بوو تا ببێتە پردێک لە نێوان تۆ و کولتوورەکەت. ئێمە لێرەین تا هیچ کوردێک لە ئەوروپا حەسرەتی خوێندنەوەی کتێب بە زمانی دایکی نەبێت.',
    'about.missions.title': 'پەیامی سێقۆڵیی ئێمە',
    'about.missions.subtitle': 'کورد بووک تەنها فرۆشگایەکی ئۆنلاین نییە. ئێمە لەسەر سێ ئامانجی پیرۆز دامەزراوین:',
    'about.missions.item1.title': 'پاراستنی ناسنامە لە تاراوگە',
    'about.missions.item1.desc': 'دەمانەوێت بە ئاسانکردنی دەستگەیشتن بە کتێبی کوردی، زمان و کولتوورمان لە دڵی خێزانە کوردەکانی دانیشتووی ئەوروپا بە زیندوویی ڕابگرین و کولتووری کتێبخوێندن پەرە پێ بدەین.',
    'about.missions.item2.title': 'پشتیوانی نووسەرانی کورد',
    'about.missions.item2.desc': 'نووسەرانی ئێمە پاسەوانی زمانی ئێمەن. ئێمە بسترێکمان فەراهەم کردووە تا بەرهەمەکانیان ببینرێت و بفرۆشرێت، تا ببێتە پشتیوانییەکی دارایی بۆ بەردەوامبوونیان لە خلقکردنی بەرهەمی بەنرخ.',
    'about.missions.item3.title': 'دڵی لێدەری ئێمە: ئایندەی منداڵان',
    'about.missions.item3.desc': 'لێرەدا چیرۆکی ئێمە جیاواز دەبێت. ئێمە باوەڕمان وایە هیچ منداڵێک نابێت بەهۆی هەژارییەوە لە نیعمەتی خوێندن و نووسین بێبەش بێت. خوێندەواری بەهێزترین چەکە بۆ بەرەنگاربوونەوەی ڕەنج و بنیاتنانی ئایندە.',
    'about.donation.title': '٪١٠٠ی قازانج بۆ پەروەردە',
    'about.donation.text': 'بە شانازییەوە ڕادەگەیەنین کە ١٠٠٪ی قازانجی فرۆشی کتێبەکان لەم ماڵپەڕەدا، ڕاستەوخۆ بۆ پشتیوانی لە پەروەردەی منداڵانی کەمدەرامەت لە کوردستان خەرج دەکرێت.',
    'about.donation.impact': 'کاتێک کتێبێک لە کورد بووک دەکڕیت، تەنها کاڵایەکی کولتووری بەدەست ناهێنیت؛ بەڵکو هاوکات سێ کاری گەورە ئەنجام دەدەیت:',
    'about.donation.point1': 'چراغی کولتووری کوردی لە ماڵەکەتدا دادەگیرسێنیت.',
    'about.donation.point2': 'پشتیوانی لە نووسەرێکی زەحمەتکێشی کورد دەکەیت.',
    'about.donation.point3': 'و لە هەمووی گرنگتر: قەڵەمێک دەخەیتە دەستی منداڵێک کە ئاواتی نووسینی هەیە.',
    'about.donation.closing': 'هەر کتێبێک کە لێرە دەفرۆشرێت، خشتێکە بۆ بنیاتنانی ئایندەیەکی ڕووناکتر بۆ منداڵانی نیشتمانمان. لەگەڵمان بن تا بەیەکەوە زانایی بچێنین و هیوا دروێنە بکەین.',
    'about.cta': 'کڕین و پشتیوانی',
    'about.ourStory': 'چیرۆکی ئێمە',
    'about.vision': 'دیدگا',
  },
  en: {
    'site.title': 'Kurdish Library',
    'site.description': 'The best online store for Kurdish books',
    'nav.home': 'Home',
    'nav.categories': 'Categories',
    'nav.books': 'Books',
    'nav.authors': 'Authors',
    'nav.arts': 'Arts & Culture',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.cart': 'Cart',
    'nav.wishlist': 'Wishlist',
    'nav.profile': 'Profile',
    'nav.menu': 'Menu',
    'nav.language': 'Language',
    'nav.search': 'Search',
    'nav.login': 'Login',
    'nav.register': 'Register',
    'header.orderStatus': 'Order Status',
    'header.account': 'Account',
    'common.search': 'Search',
    'app.name': 'Kurdish Library',
    'home.welcome': 'Welcome to Kurdish Library',
    'home.subtitle': 'The best online store for Kurdish books',
    'home.featured': 'Featured Books',
    'home.featuredSubtitle': 'Our recommendations for you',
    'home.bestsellers': 'Best Sellers',
    'home.bestsellersSubtitle': 'Most popular books among our customers',
    'home.newReleases': 'New Releases',
    'home.newReleasesSubtitle': 'Check out the latest releases',
    'home.newReleasesDesc': 'A collection of the newest and best Kurdish books',
    'homepage.welcome': 'Welcome to Kurdish Book Store',
    'homepage.subtitle': 'Discover thousands of books',
    'homepage.inspiration': 'Read, Learn, Grow',
    'homepage.newReleasesSubtitle': 'Just Released',
    'homepage.newReleasesDesc': 'Check out the newest additions to our collection',
    'hero.searchPlaceholder': 'Search for books, authors...',
    'newsletter.title': 'Join Our Literary Circle',
    'newsletter.subtitle': 'Get the latest updates, new releases, and exclusive offers delivered directly to your inbox.',
    'newsletter.placeholder': 'Enter your email',
    'newsletter.button': 'Subscribe',
    'footer.description': 'Your premier destination for Kurdish literature, culture, and history. Connecting readers with the richness of our heritage through a carefully curated selection of books.',
    'footer.newsletterDescription': 'Get the latest updates, new releases, and exclusive offers delivered directly to your inbox.',
    'footer.emailPlaceholder': 'Enter your email',
    'ads.adSpace': 'Ad Space',
    'common.by': 'By',
    'offers.limitedTime': 'Limited Time',
    'home.viewAll': 'View All',
    'hero.badge': 'New Collection 2025',
    'book.price': 'Price',
    'book.by': 'By:',
    'book.author': 'Author',
    'book.publisher': 'Publisher:',
    'book.reviews': 'Reviews',
    'book.quantity': 'Quantity:',
    'book.pages': 'Pages:',
    'book.language': 'Language:',
    'book.publishDate': 'Publication Date:',
    'book.description': 'Description',
    'book.moreInfo': 'More Info',
    'book.tags': 'Tags:',
    'book.technicalInfo': 'Technical Information',
    'book.category': 'Category',
    'book.relatedBooks': 'Related Books',
    'book.addToCart': 'Add to Cart',
    'book.buyNow': 'Buy Now',
    'book.inStock': 'In Stock',
    'book.outOfStock': 'Out of Stock',
    'book.customersAlsoBought': 'Customers also bought',
    'book.information': 'Information about the book',
    'book.giftTitle': 'Gift this book today',
    'book.giftSubtitle': 'It is very simple',
    'book.interestingTopics': 'Maybe these topics are also interesting',
    'book.fullName': 'Full Name',
    'book.binding': 'Binding',
    'book.releaseDate': 'Release Date',
    'book.ean': 'EAN',
    'book.isbn': 'ISBN',
    'book.libristoCode': 'Libristo-Code',
    'book.weight': 'Weight',
    'book.dimensions': 'Dimensions',
    'book.giftStep1': 'Put the book in your cart and choose "Send as gift"',
    'book.giftStep2': 'We send you a voucher immediately',
    'book.giftStep3': 'The book will be sent to the recipient\'s address',
    'book.deliveryPromise': 'We deliver by Christmas',
    'book.externalStock': 'External Stock',
    'book.shippingTime': 'We ship in 4-7 days',
    'book.returnPolicy': '30 days return policy',
    'book.fullDescription': 'Full description',
    'book.inclVAT': 'incl. VAT',
    'cart.title': 'Shopping Cart',
    'cart.empty': 'Your cart is empty',
    'cart.total': 'Total',
    'cart.checkout': 'Checkout',
    'cart.youMightAlsoLike': 'You Might Also Like',
    'search.title': 'Search',
    'search.placeholder': 'Enter book name, author or category...',
    'search.noResults': 'No books found',
    'search.filters': 'Filters',
    'search.sortBy': 'Sort by:',
    'search.newest': 'Newest',
    'search.oldest': 'Oldest',
    'search.nameAZ': 'Name (A-Z)',
    'search.nameZA': 'Name (Z-A)',
    'search.priceLowHigh': 'Price Low to High',
    'search.priceHighLow': 'Price High to Low',
    'search.mostPopular': 'Most Popular',
    'search.allCategories': 'All Categories',
    'search.priceRange': 'Price Range',
    'search.minPrice': 'Minimum Price',
    'search.maxPrice': 'Maximum Price',
    'search.applyFilter': 'Apply Filter',
    'search.showAll': 'Show All',
    'search.resultsFound': 'results found',
    'search.hideFilters': 'Hide Filters',
    'search.resetAll': 'Reset All',
    'search.noResultsFor': 'No books found for',
    'search.clearSearch': 'Clear Search',
    'search.loading': 'Loading search...',
    'authors.title': 'Authors',
    'authors.biography': 'Biography',
    'authors.viewProfile': 'View Profile',
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.name': 'Full Name',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.noAccount': "Don't have an account?",
    'auth.haveAccount': 'Already have an account?',
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.rememberMe': 'Remember me',
    'auth.quickTest': 'Quick Test',
    'auth.forTesting': 'For testing:',
    'auth.emailLabel': 'Email:',
    'auth.passwordLabel': 'Password:',
    'auth.error.invalidCredentials': 'Invalid email or password',
    'auth.error.emailUsed': 'This email is already in use',
    'auth.createAccount': 'Create a new account',
    'auth.orLogin': 'or Login',
    'auth.firstName': 'First Name',
    'auth.lastName': 'Last Name',
    'auth.phone': 'Phone Number',
    'auth.optional': '(Optional)',
    'auth.chooseStrongPassword': 'Choose a strong password',
    'auth.minChars': 'Must be at least 6 characters',
    'auth.creatingAccount': 'Create Account',
    'auth.termsAgreement': 'Creating an account means agreeing to',
    'auth.terms': 'Terms',
    'auth.privacyPolicy': 'Privacy Policy',
    'auth.and': 'and',
    'book.inCart': 'In Cart',
    'book.notInCart': 'Not in Cart',
    'profile.dashboard': 'Dashboard',
    'profile.orders': 'Orders',
    'profile.wishlist': 'Wishlist',
    'profile.addresses': 'Addresses',
    'profile.accountDetails': 'Account Details',
    'profile.logout': 'Logout',
    'profile.personalInfo': 'Personal Information',
    'profile.updateInfo': 'Update Information',
    'profile.save': 'Save',
    'profile.changePassword': 'Change Password',
    'profile.orderHistory': 'Order History',
    'profile.noOrders': 'No orders yet',
    'profile.orderDetails': 'Order Details',
    'profile.recentOrders': 'Recent Orders',
    'profile.settings': 'Settings',
    'profile.edit': 'Edit',
    'profile.cancel': 'Cancel',
    'profile.firstName': 'First Name',
    'profile.lastName': 'Last Name',
    'profile.email': 'Email',
    'profile.phone': 'Phone Number',
    'profile.address': 'Address',
    'profile.city': 'City',
    'profile.zipCode': 'Zip Code',
    'profile.loading': 'Loading profile...',
    'status.available': 'Available',
    'status.unavailable': 'Unavailable',
    'status.outOfStock': 'Out of Stock',
    'form.required': 'Required',
    'form.invalidEmail': 'Invalid email address',
    'form.passwordsDontMatch': 'Passwords do not match',
    'form.passwordTooShort': 'Password must be at least 6 characters',
    'common.loading': 'Loading...',
    'common.pleaseWait': 'Please wait...',
    'common.error': 'An error occurred',
    'common.success': 'Success',
    'buttons.viewAll': 'View All',
    'buttons.viewAllShort': 'All',
    'buttons.readMore': 'Read More',
    'buttons.addToCart': 'Add to Cart',
    'buttons.buyNow': 'Buy Now',
    'buttons.buy': 'Buy',
    'buttons.save': 'Save',
    'buttons.cancel': 'Cancel',
    'buttons.edit': 'Edit',
    'buttons.delete': 'Delete',
    'buttons.confirm': 'Confirm',
    'buttons.viewDetails': 'View Details',
    'categories.literature': 'Literature',
    'categories.poetry': 'Poetry',
    'categories.history': 'History',
    'categories.children': 'Children',
    'categories.education': 'Education',
    'categories.science': 'Science',
    'categories.religion': 'Religion',
    'categories.biography': 'Biography',
    'categories.philosophy': 'Philosophy',
    'categories.politics': 'Politics',
    'categories.culture': 'Culture',
    'footer.aboutUs': 'About Us',
    'footer.contactInfo': 'Contact Information',
    'footer.followUs': 'Follow Us',
    'footer.copyright': 'Copyright Kurdish Library. All rights reserved.',
    'sections.featuredBooks': 'Featured Books',
    'sections.bestSellers': 'Best Sellers',
    'sections.newReleases': 'New Releases',
    'sections.specialOffers': 'Special Offers',
    'sections.statistics': 'Statistics',
    'offers.discount': 'Up to 50% discount on selected books',
    'offers.viewOffers': 'View Offers',
    'stats.books': 'Books',
    'stats.authors': 'Authors',
    'stats.publishers': 'Publishers',
    // Admin translations
    'admin.login': 'Admin Login',
    'admin.username': 'Username',
    'admin.password': 'Password',
    'admin.enterUsername': 'Enter username',
    'admin.enterPassword': 'Enter password',
    'admin.loginButton': 'Login',
    'admin.loggingIn': 'Logging in...',
    'admin.invalidCredentials': 'Invalid username or password',
    'admin.accessPanel': 'Access the admin panel',
    'admin.demoCredentials': 'Demo Credentials:',
    'admin.panel': 'Admin Panel',
    'admin.welcome': 'Welcome Admin',
    'admin.logout': 'Logout',
    'admin.dashboard': 'Dashboard',
    'admin.manageBooks': 'Manage Books',
    'admin.manageAuthors': 'Manage Authors',
    'admin.addBook': 'Add Book',
    'admin.addAuthor': 'Add Author',
    'admin.addNewBook': 'Add New Book',
    'admin.addNewAuthor': 'Add New Author',
    'admin.title': 'Title',
    'admin.author': 'Author',
    'admin.publisher': 'Publisher',
    'admin.price': 'Price (EUR)',
    'admin.description': 'Description',
    'admin.nameKurdish': 'Name (Kurdish)',
    'admin.nameLatin': 'Name (Latin)',
    'admin.birthYear': 'Birth Year',
    'admin.deathYear': 'Death Year (Optional)',
    'admin.biographyKurdish': 'Biography (Kurdish)',
    'admin.totalBooks': 'Total Books',
    'admin.totalAuthors': 'Authors',
    'admin.totalReviews': 'Reviews',
    'admin.avgRating': 'Avg Rating',
    'admin.recentActivity': 'Recent Activity',
    'admin.bookAdded': 'Book added!',
    'admin.authorAdded': 'Author added!',
    'admin.actions': 'Actions',
    'admin.rating': 'Rating',
    'admin.books': 'books',
    'stats.customers': 'Happy Customers',
    'description.categories': 'Books organized by topics and categories',
    'footer.aboutTitle': 'About Us',
    'footer.aboutDescription': 'Kurdish Library is the best online store for Kurdish books',
    'footer.quickLinks': 'Quick Links',
    'footer.customerService': 'Customer Service',
    'footer.contact': 'Contact',
    'footer.newsletter': 'Newsletter',
    'footer.subscribe': 'Subscribe',
    'auth.orders': 'Orders',
    'auth.favorites': 'Favorites',
    'auth.logout': 'Logout',
    'cart.itemCount': 'Items:',
    'cart.subtotal': 'Subtotal:',
    'cart.shipping': 'Shipping:',
    'cart.shippingFree': 'Free',
    'cart.continueShopping': 'Continue Shopping',
    'cart.emptyMessage': 'You haven\'t added any books to your cart yet',
    'cart.clearCart': 'Clear Cart',
    'cart.orderSummary': 'Order Summary',
    'cart.freeShipping': 'Free Shipping',
    'cart.returns': '7-Day Returns',
    'cart.buyerProtection': 'Buyer Protection',
    'cart.remove': 'Remove',
    'footer.shipping': 'Shipping',
    'footer.returns': 'Returns',
    'footer.faq': 'FAQ',
    'footer.help': 'Help',
    'footer.privacy': 'Privacy Policy',
    'footer.cookies': 'Cookie Policy',
    'books.subtitle': 'Discover Kurdish books collection',
    'books.category': 'Category',
    'books.search': 'Search',
    'books.searchPlaceholder': 'Search by title or author...',
    'books.sortBy': 'Sort by',
    'books.sortName': 'Name',
    'books.sortPrice': 'Price',
    'books.sortRating': 'Rating',
    'books.sortYear': 'Year',
    'books.found': 'Found:',
    'books.noResults': 'No books found',
    'books.noResultsMessage': 'Try changing your search terms or filters',
    'books.inStockOnly': 'In Stock Only',
    'books.publishers': 'Publishers',
    'books.all': 'All',
    'books.authors': 'Authors',
    'books.searchPlaceholderLong': 'Search by title, author, ISBN...',
    'books.results': 'Results',
    'books.sortBestselling': 'Bestselling',
    'books.sortNewest': 'Newest',
    'books.sortPriceLowHigh': 'Price: Low to High',
    'books.sortPriceHighLow': 'Price: High to Low',
    'authors.subtitle': 'Meet renowned Kurdish authors',
    'authors.search': 'Search authors...',
    'authors.sortBy': 'Sort by',
    'authors.sortName': 'Name',
    'authors.sortBooks': 'Books',
    'authors.sortYear': 'Birth Year',
    'authors.found': 'authors found',
    'authors.birthYear': 'Birth Year:',
    'authors.nationality': 'Nationality:',
    'authors.noBooks': 'No books available',
    'authors.noAuthorsFound': 'No authors found',
    'authors.popularAuthors': 'Popular Authors',
    'authors.clearSearch': 'Clear Search',
    'authors.noAuthorsMessage': 'Try using different search terms',
    'authors.book': 'book',
    'authors.books': 'books',
    'authors.moreBooks': 'more books',
    'authors.literaryFigures': 'Literary Figures',
    'authors.bibliography': 'Bibliography',
    'authors.born': 'Born',
    'authors.noBooksAvailable': 'No books available at the moment',
    'category.empty': 'This category is currently empty',
    'status.bestseller': 'Bestseller',
    'status.featured': 'Featured',
    'status.newRelease': 'New Release',
    'status.sale': 'Sale',
    'status.limited': 'Limited',
    'categories.all': 'All Categories',
    'wishlist.title': 'Wishlist',
    'wishlist.items': 'items',
    'wishlist.continueShopping': 'Continue Shopping',
    'wishlist.empty': 'Your wishlist is empty',
    'wishlist.emptyMessage': 'You haven\'t added any books to your wishlist yet. Browse books and add your favorites here.',
    'wishlist.browseBooks': 'Browse Books',
    'wishlist.addToCart': 'Add to Cart',
    'wishlist.remove': 'Remove',
    'checkout.information': 'Information',
    'checkout.shipping': 'Shipping',
    'checkout.payment': 'Payment',
    'checkout.contactInfo': 'Contact Information',
    'checkout.shippingAddress': 'Shipping Address',
    'checkout.paymentMethod': 'Payment Method',
    'checkout.orderPlaced': 'Order Placed Successfully',
    'checkout.orderId': 'ORDER ID',
    'checkout.thankYou': 'Thank you for your purchase. We will send you a confirmation email shortly.',
    'checkout.returnHome': 'Return Home',
    'checkout.viewOrders': 'View Orders',
    'checkout.back': 'Back',
    'checkout.nextStep': 'Next Step',
    'checkout.placeOrder': 'Place Order',
    'checkout.processing': 'Processing...',
    'checkout.creditCard': 'Credit Card',
    'checkout.cashOnDelivery': 'Cash on Delivery',
    'checkout.orderSummary': 'Order Summary',
    'checkout.subtotal': 'Subtotal',
    'checkout.total': 'Total',
    'checkout.free': 'Free',
    'checkout.qty': 'Qty',
    'contact.title': 'Get in Touch',
    'contact.subtitle': 'We\'d love to hear from you. Here\'s how you can reach us.',
    'contact.form.name': 'Your Name',
    'contact.form.email': 'Email Address',
    'contact.form.subject': 'Subject',
    'contact.form.message': 'Message',
    'contact.form.submit': 'Send Message',
    'contact.form.submitting': 'Sending...',
    'contact.form.success': 'Message sent successfully! We\'ll get back to you soon.',
    'contact.form.error': 'Something went wrong. Please try again.',
    'contact.info.title': 'Contact Information',
    'contact.info.email': 'info@kurdbook.com',
    'contact.info.phone': '+49 123 456 789',
    'contact.info.address': 'Berlin, Germany',
    'contact.info.hours': 'Mon-Fri: 9:00 AM - 6:00 PM',
    'contact.faq.title': 'Frequently Asked Questions',
    'contact.faq.q1': 'Do you ship internationally?',
    'contact.faq.a1': 'Yes, we ship to most countries in Europe and worldwide.',
    'contact.faq.q2': 'How long does delivery take?',
    'contact.faq.a2': 'Usually 3-5 business days within Europe.',
    'contact.faq.q3': 'Can I return a book?',
    'contact.faq.a3': 'Yes, within 14 days of receipt if the book is in original condition.',
    'about.title': 'Beyond a Bookstore; A Nest for Culture and Hope',
    'about.subtitle': 'Who we are and why we are here?',
    'about.intro': 'In the heart of Europe, miles away from the mountains of our homeland, we felt a great void. Access to Kurdish books, this treasure of our language and identity, was difficult or impossible for many of us in the diaspora. Kurd Book was born to be a bridge between you and your culture. We are here so that no Kurd in Europe longs for reading books in their mother tongue.',
    'about.missions.title': 'Our Threefold Mission',
    'about.missions.subtitle': 'Kurd Book is not just an online store. We are built on three sacred goals:',
    'about.missions.item1.title': 'Preserving Identity in Diaspora',
    'about.missions.item1.desc': 'We want to keep our language and culture alive in the hearts of Kurdish families living in Europe by facilitating access to Kurdish books and promoting the culture of reading.',
    'about.missions.item2.title': 'Supporting Kurdish Authors',
    'about.missions.item2.desc': 'Our authors are the guardians of our language. We have provided a platform for their works to be seen and sold, providing financial support for them to continue creating valuable works.',
    'about.missions.item3.title': 'Our Beating Heart: Children\'s Future',
    'about.missions.item3.desc': 'This is where our story becomes different. We believe no child should be deprived of reading and writing due to poverty. Literacy is the strongest weapon to fight suffering and build the future.',
    'about.donation.title': '100% of Profits for Education',
    'about.donation.text': 'We proudly announce that 100% of the profits from book sales on this website are directly spent on supporting the education of underprivileged children in Kurdistan.',
    'about.donation.impact': 'When you buy a book from Kurd Book, you are not just buying a cultural product; you are doing three great things at once:',
    'about.donation.point1': 'You light the lamp of Kurdish culture in your home.',
    'about.donation.point2': 'You support a hardworking Kurdish author.',
    'about.donation.point3': 'Most importantly: You put a pen in the hand of a child who dreams of writing.',
    'about.donation.closing': 'Every book sold here is a brick for building a brighter future for our land\'s children. Join us to plant knowledge and harvest hope together.',
    'about.cta': 'Shop Now & Support',
    'about.ourStory': 'Our Story',
    'about.vision': 'The Vision',
  },
  kmr: {
    'site.title': 'Pirtûkxaneya Kurdî',
    'site.description': 'Baştirîn firotgeha serhêl ji bo pirtûkên Kurdî',
    'nav.home': 'Mal',
    'nav.categories': 'Kategorî',
    'nav.books': 'Pirtûk',
    'nav.authors': 'Nivîskar',
    'nav.arts': 'Huner û Çand',
    'nav.about': 'Derbar',
    'nav.contact': 'Têkilî',
    'nav.cart': 'Selik',
    'nav.wishlist': 'Lîsteya Daxwazan',
    'nav.profile': 'Profîl',
    'nav.menu': 'Menu',
    'nav.language': 'Ziman',
    'nav.search': 'Lêgerîn',
    'nav.login': 'Têkeve',
    'nav.register': 'Tomar bike',
    'header.orderStatus': 'Rewşa Siparîşê',
    'header.account': 'Hesab',
    'common.search': 'Lêgerîn',
    'app.name': 'Pirtûkxaneya Kurdî',
    'home.welcome': 'Bi xêr hatî Pirtûkxaneya Kurdî',
    'home.subtitle': 'Baştirîn firotgeha serhêl ji bo pirtûkên Kurdî',
    'home.featured': 'Pirtûkên Taybet',
    'home.featuredSubtitle': 'Pêşniyarên me ji bo we',
    'home.bestsellers': 'Herî Zêde Firotî',
    'home.bestsellersSubtitle': 'Pirtûkên herî populer li cem kiriyaran',
    'home.newReleases': 'Weşanên Nû',
    'home.newReleasesSubtitle': 'Weşanên herî dawî bibînin',
    'home.newReleasesDesc': 'Komek ji pirtûkên Kurdî yên herî nû û baştirîn',
    'offers.limitedTime': 'Demek Sînorkirî',
    'home.viewAll': 'Hemûyan Bibîne',
    'hero.badge': 'Koleksiyona Nû 2025',
    'book.price': 'Biha',
    'book.by': 'Ji aliyê:',
    'book.author': 'Nivîskar',
    'book.publisher': 'Weşanxane:',
    'book.reviews': 'Nirxandin',
    'book.quantity': 'Hejmar:',
    'book.pages': 'Rûpel:',
    'book.language': 'Ziman:',
    'book.publishDate': 'Dîroka Weşanê:',
    'book.description': 'Danasîn',
    'book.moreInfo': 'Zêdetir Agahî',
    'book.tags': 'Etîket:',
    'book.technicalInfo': 'Agahiyên Teknîkî',
    'book.category': 'Kategorî',
    'book.relatedBooks': 'Pirtûkên Têkildar',
    'book.addToCart': 'Li Selikê Zêde Bike',
    'book.buyNow': 'Niha Bikire',
    'book.inStock': 'Li Stokê Heye',
    'book.outOfStock': 'Li Stokê Nîne',
    'book.customersAlsoBought': 'Kiriyarên din ev jî kirîn',
    'book.information': 'Agahî derbarê pirtûkê',
    'book.giftTitle': 'Vê pirtûkê bike diyarî',
    'book.giftSubtitle': 'Gelek hêsan e',
    'book.interestingTopics': 'Dibe ku ev mijar jî bala te bikişînin',
    'book.fullName': 'Navê Tevahî',
    'book.binding': 'Berg',
    'book.releaseDate': 'Dîroka Weşanê',
    'book.ean': 'EAN',
    'book.isbn': 'ISBN',
    'book.libristoCode': 'Koda Libristo',
    'book.weight': 'Giranî',
    'book.dimensions': 'Pîvan',
    'book.giftStep1': 'Pirtûkê têxe selikê û "Weke diyarî bişîne" hilbijêre',
    'book.giftStep2': 'Em ê yekser fîşekê ji te re bişînin',
    'book.giftStep3': 'Pirtûk dê ji navnîşana wergir re were şandin',
    'book.deliveryPromise': 'Radestkirin berî Sersalê',
    'book.externalStock': 'Stoka Derve',
    'book.shippingTime': 'Şandin di 4-7 rojan de',
    'book.returnPolicy': 'Mafê vegerandinê 30 roj',
    'book.fullDescription': 'Danasîna tevahî',
    'book.inclVAT': 'tevî VAT',
    'cart.title': 'Selika Kirînê',
    'cart.empty': 'Selika we vala ye',
    'cart.total': 'Giştî',
    'cart.checkout': 'Kirînê Temam Bike',
    'cart.youMightAlsoLike': 'Pirtûkên din ku dibe bala te bikişînin',
    'search.title': 'Lêgerîn',
    'search.placeholder': 'Navê pirtûkê, nivîskar an kategorî binivîse...',
    'search.noResults': 'Ti pirtûk nehat dîtin',
    'search.filters': 'Fîlter',
    'search.sortBy': 'Rêz bike li gorî:',
    'search.newest': 'Herî Nû',
    'search.oldest': 'Herî Kevn',
    'search.nameAZ': 'Nav (A-Z)',
    'search.nameZA': 'Nav (Z-A)',
    'search.priceLowHigh': 'Biha Kêm bo Zêde',
    'search.priceHighLow': 'Biha Zêde bo Kêm',
    'search.mostPopular': 'Herî Populer',
    'search.allCategories': 'Hemû Kategorî',
    'search.priceRange': 'Rêjeya Bihayê',
    'search.minPrice': 'Bihayê Kêmtirîn',
    'search.maxPrice': 'Bihayê Zêdetirîn',
    'search.applyFilter': 'Fîlterê Bikar Bîne',
    'search.showAll': 'Hemûyan Nîşan Bide',
    'search.resultsFound': 'encam hatin dîtin',
    'search.hideFilters': 'Fîlteran Veşêre',
    'search.resetAll': 'Hemûyan Paqij Bike',
    'search.noResultsFor': 'Ti pirtûk nehat dîtin ji bo',
    'search.clearSearch': 'Lêgerînê Paqij Bike',
    'search.loading': 'Lêgerîn...',
    'authors.title': 'Nivîskar',
    'authors.biography': 'Jînenîgarî',
    'authors.viewProfile': 'Profîlê Bibîne',
    'auth.login': 'Têkeve',
    'auth.register': 'Tomar bike',
    'auth.email': 'E-name',
    'auth.password': 'Şîfre',
    'auth.confirmPassword': 'Şîfre piştrast bike',
    'auth.name': 'Navê Tevahî',
    'auth.forgotPassword': 'Şîfre ji bîr çû?',
    'auth.noAccount': 'Hesabê te nîne?',
    'auth.haveAccount': 'Hesabê te heye?',
    'auth.signIn': 'Têkeve',
    'auth.signUp': 'Tomar bike',
    'auth.rememberMe': 'Min bi bîr bîne',
    'auth.quickTest': 'Testa Bilez',
    'auth.forTesting': 'Ji bo testê:',
    'auth.emailLabel': 'E-name:',
    'auth.passwordLabel': 'Şîfre:',
    'auth.error.invalidCredentials': 'E-name an şîfre şaş e',
    'auth.error.emailUsed': 'Ev e-name berê hatiye bikaranîn',
    'auth.createAccount': 'Hesabek nû çêbike',
    'auth.orLogin': 'an Têkeve',
    'auth.firstName': 'Nav',
    'auth.lastName': 'Paşnav',
    'auth.phone': 'Hejmara Telefonê',
    'auth.optional': '(Bijarî)',
    'auth.chooseStrongPassword': 'Şîfreyek bihêz hilbijêre',
    'auth.minChars': 'Divê kêmî 6 tîpan be',
    'auth.creatingAccount': 'Hesab tê çêkirin',
    'auth.termsAgreement': 'Çêkirina hesab tê wateya qebûlkirina',
    'auth.terms': 'Mercan',
    'auth.privacyPolicy': 'Siyaseta Taybetmendiyê',
    'auth.and': 'û',
    'book.inCart': 'Li Selikê',
    'book.notInCart': 'Ne li Selikê ye',
    'profile.dashboard': 'Dashboard',
    'profile.orders': 'Siparîş',
    'profile.wishlist': 'Lîsteya Daxwazan',
    'profile.addresses': 'Navnîşan',
    'profile.accountDetails': 'Agahiyên Hesabê',
    'profile.logout': 'Derkeve',
    'profile.personalInfo': 'Agahiyên Kesane',
    'profile.updateInfo': 'Agahiyan Nû Bike',
    'profile.save': 'Tomar bike',
    'profile.changePassword': 'Şîfre Biguherîne',
    'profile.orderHistory': 'Dîroka Siparîşan',
    'profile.noOrders': 'Hîn siparîş nînin',
    'profile.orderDetails': 'Agahiyên Siparîşê',
    'profile.recentOrders': 'Siparîşên Dawî',
    'profile.settings': 'Mîheng',
    'profile.edit': 'Biguherîne',
    'profile.cancel': 'Betal bike',
    'profile.firstName': 'Nav',
    'profile.lastName': 'Paşnav',
    'profile.email': 'E-name',
    'profile.phone': 'Hejmara Telefonê',
    'profile.address': 'Navnîşan',
    'profile.city': 'Bajar',
    'profile.zipCode': 'Koda Postayê',
    'profile.loading': 'Profîl tê barkirin...',
    'status.available': 'بەردەستە',
    'status.unavailable': 'ناوبەردەست',
    'status.outOfStock': 'لە کۆمەڵ چووە',
    'form.required': 'Pêwîst e',
    'form.invalidEmail': 'Navnîşana e-nameyê nederbasdar e',
    'form.passwordsDontMatch': 'Şîfre li hev nayên',
    'form.passwordTooShort': 'Şîfre divê kêmî 6 tîpan be',
    'common.loading': 'Tê barkirin...',
    'common.pleaseWait': 'Ji kerema xwe bisekine...',
    'common.error': 'Çewtiyek çêbû',
    'common.success': 'Serkeftî',
    'buttons.viewAll': 'Hemûyan Bibîne',
    'buttons.viewAllShort': 'Hemû',
    'buttons.readMore': 'Zêdetir Bixwîne',
    'buttons.addToCart': 'Li Selikê Zêde Bike',
    'buttons.buyNow': 'Niha Bikire',
    'buttons.buy': 'Bikire',
    'buttons.save': 'Tomar bike',
    'buttons.cancel': 'Betal bike',
    'buttons.edit': 'Biguherîne',
    'buttons.delete': 'Jê bibe',
    'buttons.confirm': 'Piştrast bike',
    'buttons.viewDetails': 'Agahiyan Bibîne',
    'categories.literature': 'Wêje',
    'categories.poetry': 'Helbest',
    'categories.history': 'Dîrok',
    'categories.children': 'Zarok',
    'categories.education': 'Perwerde',
    'categories.science': 'Zanist',
    'categories.religion': 'Ol',
    'categories.biography': 'Jînenîgarî',
    'categories.philosophy': 'Felsefe',
    'categories.politics': 'Siyaset',
    'categories.culture': 'Çand',
    'footer.aboutUs': 'Derbarê Me',
    'footer.contactInfo': 'Agahiyên Têkiliyê',
    'footer.followUs': 'Me bişopînin',
    'footer.copyright': 'Mafê Çapê Pirtûkxaneya Kurdî. Hemû maf parastî ne.',
    'sections.featuredBooks': 'Pirtûkên Taybet',
    'sections.bestSellers': 'Herî Zêde Firotî',
    'sections.newReleases': 'Weşanên Nû',
    'sections.specialOffers': 'Pêşniyarên Taybet',
    'sections.statistics': 'Amar',
    'offers.discount': 'Heta %50 daxistin li ser pirtûkên hilbijartî',
    'offers.viewOffers': 'Pêşniyaran Bibîne',
    'stats.books': 'Pirtûk',
    'stats.authors': 'Nivîskar',
    'stats.publishers': 'Weşanxane',
    // Admin translations
    'admin.login': 'Têketina Rêveber',
    'admin.username': 'Navê Bikarhêner',
    'admin.password': 'Şîfre',
    'admin.enterUsername': 'Navê bikarhêner binivîse',
    'admin.enterPassword': 'Şîfre binivîse',
    'admin.loginButton': 'Têkeve',
    'admin.loggingIn': 'Têdikeve...',
    'admin.invalidCredentials': 'Navê bikarhêner an şîfre şaş e',
    'admin.accessPanel': 'Gihîştina panela rêveber',
    'admin.demoCredentials': 'Agahiyên Demo:',
    'admin.panel': 'Panela Rêveber',
    'admin.welcome': 'Bi xêr hatî Rêveber',
    'admin.logout': 'Derkeve',
    'admin.dashboard': 'Dashboard',
    'admin.manageBooks': 'Pirtûkan Birêve Bibe',
    'admin.manageAuthors': 'Nivîskaran Birêve Bibe',
    'admin.addBook': 'Pirtûk Zêde Bike',
    'admin.addAuthor': 'Nivîskar Zêde Bike',
    'admin.addNewBook': 'Pirtûka Nû Zêde Bike',
    'admin.addNewAuthor': 'Nivîskarê Nû Zêde Bike',
    'admin.title': 'Sernav',
    'admin.author': 'Nivîskar',
    'admin.publisher': 'Weşanxane',
    'admin.price': 'Biha (EUR)',
    'admin.description': 'Danasîn',
    'admin.nameKurdish': 'Nav (Kurdî)',
    'admin.nameLatin': 'Nav (Latînî)',
    'admin.birthYear': 'Sala Jidayikbûnê',
    'admin.deathYear': 'Sala Mirinê (Bijarî)',
    'admin.biographyKurdish': 'Jînenîgarî (Kurdî)',
    'admin.totalBooks': 'Tevahiya Pirtûkan',
    'admin.totalAuthors': 'Nivîskar',
    'admin.totalReviews': 'Nirxandin',
    'admin.avgRating': 'Nirxandina Navîn',
    'admin.recentActivity': 'Çalakiyên Dawî',
    'admin.bookAdded': 'Pirtûk hat zêdekirin!',
    'admin.authorAdded': 'Nivîskar hat zêdekirin!',
    'admin.actions': 'Çalakî',
    'admin.rating': 'Nirxandin',
    'admin.books': 'Pirtûk',
    'stats.customers': 'Kiriyarên Dilxweş',
    'description.categories': 'Pirtûk li gorî mijar û kategoriyan hatine rêzkirin',
    'footer.aboutTitle': 'Derbarê Me',
    'footer.aboutDescription': 'Pirtûkxaneya Kurdî baştirîn firotgeha serhêl e ji bo pirtûkên Kurdî',
    'footer.quickLinks': 'Lînkên Bilez',
    'footer.customerService': 'Xizmeta Kiriyaran',
    'footer.contact': 'Têkilî',
    'footer.newsletter': 'Nûçename',
    'footer.newsletterDescription': 'Agahdar be li ser pirtûkên nû û pêşniyarên taybet',
    'footer.subscribe': 'Abone be',
    'auth.profile': 'Profîl',
    'auth.orders': 'Siparîş',
    'auth.favorites': 'Bijare',
    'auth.logout': 'Derkeve',
    'cart.itemCount': 'Berhem:',
    'cart.subtotal': 'Bihayê Giştî:',
    'cart.shipping': 'Barkirin:',
    'cart.shippingFree': 'Bêpere',
    'cart.continueShopping': 'Kirînê Berdewam Bike',
    'cart.emptyMessage': 'Te hîn ti pirtûk li selika xwe zêde nekiriye',
    'cart.clearCart': 'Selikê Vala Bike',
    'cart.orderSummary': 'Kurteya Siparîşê',
    'cart.freeShipping': 'Barkirina Bêpere',
    'cart.returns': 'Vegerandina 7 Rojan',
    'cart.buyerProtection': 'Parastina Kiriyar',
    'cart.remove': 'Jê bibe',
    'footer.shipping': 'Barkirin',
    'footer.returns': 'Vegerandin',
    'footer.faq': 'Pirsên Pir Tên Pirsîn',
    'footer.help': 'Alîkarî',
    'footer.emailPlaceholder': 'E-nameya xwe binivîse...',
    'footer.privacy': 'Siyaseta Taybetmendiyê',
    'footer.terms': 'Mercên Bikaranînê',
    'footer.cookies': 'Siyaseta Çerezan',
    'books.subtitle': 'Koleksiyona pirtûkên Kurdî bibîne',
    'books.category': 'Kategorî',
    'books.search': 'Lêgerîn',
    'books.searchPlaceholder': 'Li gorî sernav an nivîskar bigere...',
    'books.sortBy': 'Rêz bike li gorî',
    'books.sortName': 'Nav',
    'books.sortPrice': 'Biha',
    'books.sortRating': 'Nirxandin',
    'books.sortYear': 'Sal',
    'books.found': 'Hatin dîtin:',
    'books.noResults': 'Pirtûk nehat dîtin',
    'books.noResultsMessage': 'Hewl bide peyvên lêgerînê an fîlteran biguherînî',
    'books.inStockOnly': 'Tenê Yên Li Stokê',
    'books.publishers': 'Weşanxane',
    'books.all': 'Hemû',
    'books.authors': 'Nivîskar',
    'books.searchPlaceholderLong': 'Lêgerîn li gorî sernav, nivîskar, ISBN...',
    'books.results': 'Encam',
    'books.sortBestselling': 'Herî Zêde Firotî',
    'books.sortNewest': 'Herî Nû',
    'books.sortPriceLowHigh': 'Biha: Kêm bo Zêde',
    'books.sortPriceHighLow': 'Biha: Zêde bo Kêm',
    'authors.subtitle': 'Nivîskarên Kurd ên navdar nas bike',
    'authors.search': 'Li nivîskaran bigere...',
    'authors.sortBy': 'Rêz bike li gorî',
    'authors.sortName': 'Nav',
    'authors.sortBooks': 'Pirtûk',
    'authors.sortYear': 'Sala Jidayikbûnê',
    'authors.found': 'nivîskar hatin dîtin',
    'authors.birthYear': 'Sala Jidayikbûnê:',
    'authors.nationality': 'Neteweyî:',
    'authors.noBooks': 'Pirtûk nînin',
    'authors.noAuthorsFound': 'Nivîskar nehat dîtin',
    'authors.popularAuthors': 'Nivîskarên Populer',
    'authors.clearSearch': 'Lêgerînê Paqij Bike',
    'authors.noAuthorsMessage': 'Hewl bide peyvên lêgerînê yên cûda bikar bînî',
    'authors.book': 'pirtûk',
    'authors.books': 'pirtûk',
    'authors.moreBooks': 'pirtûkên din',
    'authors.literaryFigures': 'Kesayetiyên Wêjeyî',
    'authors.bibliography': 'Pirtûknasî',
    'authors.born': 'Jidayikbûyî',
    'authors.noBooksAvailable': 'Di vê demê de ti pirtûk tune',
    'category.empty': 'Ev kategorî niha vala ye',
    'status.bestseller': 'Herî Zêde Firotî',
    'status.featured': 'Taybet',
    'status.newRelease': 'Weşana Nû',
    'status.sale': 'Daxistin',
    'status.limited': 'Sînorkirî',
    'categories.all': 'Hemû Kategorî',
    'wishlist.title': 'Lîsteya Daxwazan',
    'wishlist.items': 'pirtûk',
    'wishlist.continueShopping': 'Kirînê Berdewam Bike',
    'wishlist.empty': 'Lîsteya daxwazên te vala ye',
    'wishlist.emptyMessage': 'Te hîn ti pirtûk li lîsteya daxwazên xwe zêde nekiriye. Li pirtûkan bigere û yên bijare lê zêde bike.',
    'wishlist.browseBooks': 'Li Pirtûkan Bigere',
    'wishlist.addToCart': 'Li Selikê Zêde Bike',
    'wishlist.remove': 'Jê bibe',
    'checkout.information': 'Agahî',
    'checkout.shipping': 'Barkirin',
    'checkout.payment': 'Tezmînat',
    'checkout.contactInfo': 'Agahiyên Têkiliyê',
    'checkout.shippingAddress': 'Navnîşana Barkirinê',
    'checkout.paymentMethod': 'Rêbaza Tezmînatê',
    'checkout.orderPlaced': 'Siparîş Serkeftî Bû',
    'checkout.orderId': 'HEJMARA SIPARÎŞÊ',
    'checkout.thankYou': 'Spas ji bo kirîna te. Em ê di demek kurt de e-nameyek piştrastkirinê ji te re bişînin.',
    'checkout.returnHome': 'Vegere Malê',
    'checkout.viewOrders': 'Siparîşan Bibîne',
    'checkout.back': 'Vegere',
    'checkout.nextStep': 'Gava Pêş',
    'checkout.placeOrder': 'Siparîşê Temam Bike',
    'checkout.processing': 'Tê pêvajokirin...',
    'checkout.creditCard': 'Karta Krediyê',
    'checkout.cashOnDelivery': 'Tezmînat li ber Derî',
    'checkout.orderSummary': 'Kurteya Siparîşê',
    'checkout.subtotal': 'Bihayê Giştî',
    'checkout.total': 'Giştî',
    'checkout.free': 'Bêpere',
    'checkout.qty': 'Hjm',
    'contact.title': 'Têkilî',
    'contact.subtitle': 'Em kêfxweş dibin ku ji te bibihîzin. Li vir tu dikarî xwe bigihînî me.',
    'contact.form.name': 'Navê Tevahî',
    'contact.form.email': 'E-name',
    'contact.form.subject': 'Mijar',
    'contact.form.message': 'Peyam',
    'contact.form.submit': 'Peyamê Bişîne',
    'contact.form.submitting': 'Tê şandin...',
    'contact.form.success': 'Peyam bi serkeftî hat şandin! Em ê di demek kurt de bersiva te bidin.',
    'contact.form.error': 'Çewtiyek çêbû. Ji kerema xwe dîsa hewl bide.',
    'contact.info.title': 'Agahiyên Têkiliyê',
    'contact.info.email': 'info@kurdbook.com',
    'contact.info.phone': '+49 123 456 789',
    'contact.info.address': 'Berlin, Almanya',
    'contact.info.hours': 'Duşem - În: 9:00 Sibê - 6:00 Êvarê',
    'contact.faq.title': 'Pirsên Pir Tên Pirsîn',
    'contact.faq.q1': 'Gelo hûn dişînin derveyî welat?',
    'contact.faq.a1': 'Erê, em dişînin piraniya welatên Ewropa û cîhanê.',
    'contact.faq.q2': 'Radestkirin çiqas dem digire?',
    'contact.faq.a2': 'Bi gelemperî 3-5 rojên xebatê li nav Ewropayê.',
    'contact.faq.q3': 'Gelo ez dikarim pirtûkek vegerînim?',
    'contact.faq.a3': 'Erê, di nava 14 rojan de piştî wergirtinê, heger pirtûk di rewşa xwe ya orjînal de be.',
    'about.title': 'Zêdetirî Pirtûkfiroşiyekê; Hêlînek ji bo Çand û Hêviyê',
    'about.subtitle': 'Em kî ne û çima li vir in?',
    'about.intro': 'Li dilê Ewropayê, bi kîlometreyan dûrî çiyayên welatê me, me valahiyeke mezin hîs kir. Gihîştina pirtûkên Kurdî, ku xezîneya ziman û nasnameya me ye, ji bo gelek ji me li diyasporayê dijwar an ne gengaz bû. Kurd Book ji dayik bû da ku bibe pirek di navbera te û çanda te de. Em li vir in da ku ti Kurdek li Ewropayê hesreta xwendina pirtûkan bi zimanê dayikê neke.',
    'about.missions.title': 'Peyama Me ya Sêalî',
    'about.missions.subtitle': 'Kurd Book ne tenê firotgeheke serhêl e. Em li ser sê armancên pîroz hatine avakirin:',
    'about.missions.item1.title': 'Parastina Nasnameyê li Diyasporayê',
    'about.missions.item1.desc': 'Em dixwazin bi hêsankirina gihîştina pirtûkên Kurdî, ziman û çanda xwe di dilê malbatên Kurd ên li Ewropayê dijîn de zindî bihêlin û çanda pirtûkxwendinê pêş bixin.',
    'about.missions.item2.title': 'Piştgiriya Nivîskarên Kurd',
    'about.missions.item2.desc': 'Nivîskarên me parêzvanên zimanê me ne. Me platformek peyda kiriye da ku berhemên wan werin dîtin û firotin, da ku bibe piştgiriyeke darayî ji bo berdewamiya wan di afirandina berhemên hêja de.',
    'about.missions.item3.title': 'Dilê Me yê Lêdide: Pêşeroja Zarokan',
    'about.missions.item3.desc': 'Li vir çîroka me cûda dibe. Em bawer dikin ku ti zarokek divê ji ber xizaniyê ji nîmeta xwendin û nivîsandinê bêpar nemîne. Xwendewarî çeka herî xurt e ji bo têkoşîna li dijî êşê û avakirina pêşerojê.',
    'about.donation.title': '%100 Qezenc ji bo Perwerdehiyê',
    'about.donation.text': 'Bi şanazî em radigihînin ku %100 qezenca firotina pirtûkan li ser vê malperê, rasterast ji bo piştgiriya perwerdehiya zarokên kêmderamet li Kurdistanê tê xerckirin.',
    'about.donation.impact': 'Dema ku tu pirtûkekê ji Kurd Book dikirî, tu ne tenê berhemeke çandî bi dest dixî; belkî di heman demê de sê karên mezin pêk tînî:',
    'about.donation.point1': 'Çiraya çanda Kurdî li mala xwe vêdixî.',
    'about.donation.point2': 'Piştgiriya nivîskarekî Kurd ê kedkar dikî.',
    'about.donation.point3': 'Û ya herî girîng: Pênûsekê dixî destê zarokekî ku xeyala nivîsandinê dike.',
    'about.donation.closing': 'Her pirtûkek ku li vir tê firotin,xîştek e ji bo avakirina pêşerojeke ronaktir ji bo zarokên welatê me. Bi me re bin da ku em bi hev re zanînê biçînin û hêviyê biçinîn.',
    'about.cta': 'Bikire û Piştgirî Bike',
    'about.ourStory': 'Çîroka Me',
    'about.vision': 'Dîtin',
    'homepage.welcome': 'Bi xêr hatî Pirtûkxaneya Kurdî',
    'homepage.subtitle': 'Baştirîn firotgeha serhêl ji bo pirtûkên Kurdî',
    'homepage.inspiration': 'Îlhama xwe bibîne',
    'homepage.newReleasesSubtitle': 'Weşanên herî dawî bibînin',
    'homepage.newReleasesDesc': 'Komek ji pirtûkên Kurdî yên herî nû û baştirîn',
    'hero.searchPlaceholder': 'Li pirtûk, nivîskaran bigere...',
    'newsletter.title': 'Nûçename',
    'newsletter.subtitle': 'Ji bo nûçeyên herî dawî qeyd bibe',
    'newsletter.placeholder': 'E-nameya xwe binivîse',
    'newsletter.button': 'Abone be',
    'footer.description': 'Pirtûkxaneya Kurdî baştirîn firotgeha serhêl e ji bo pirtûkên Kurdî',
    'ads.adSpace': 'Cihê Reklamê',
    'common.by': 'Ji aliyê',
  }
};

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [currentLanguage, setCurrentLanguage] = useState<Language>('ku');

  // Load language from localStorage on component mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && ['ku', 'en', 'kmr'].includes(savedLanguage)) {
      setCurrentLanguage(savedLanguage);
    }
  }, []);

  // Update html dir and lang attributes when language changes
  useEffect(() => {
    const dir = currentLanguage === 'ku' ? 'rtl' : 'ltr';
    document.documentElement.dir = dir;
    document.documentElement.lang = currentLanguage;
  }, [currentLanguage]);

  const setLanguage = (lang: Language) => {
    setCurrentLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    const langData = (translations as any)[currentLanguage];
    return langData[key] || key;
  };

  const dir = currentLanguage === 'ku' ? 'rtl' : 'ltr';
  const isRTL = dir === 'rtl';

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, t, dir, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}