'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'ku' | 'en' | 'de';

interface LanguageContextType {
  currentLanguage: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: 'rtl' | 'ltr';
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation data
const translations = {
  ku: {
    'site.title': 'کتابخانەی کوردی',
    'site.description': 'باشترین فرۆشگای ئۆنلاین بۆ کتابەکانی کوردی',
    'nav.home': 'سەرەتا',
    'nav.categories': 'پۆلەکان',
    'nav.books': 'کتابەکان',
    'nav.authors': 'نووسەران',
    'nav.about': 'دەربارە',
    'nav.contact': 'پەیوەندی',
    'nav.cart': 'سەبەتە',
    'nav.wishlist': 'لیستی خوازراوی',
    'nav.profile': 'پرۆفایل',
    'nav.menu': 'مینو',
    'nav.language': 'زمان',
    'nav.search': 'گەڕان',
    'nav.login': 'چوونە ژوورەوە',
    'nav.register': 'تۆمارکردن',
    'header.orderStatus': 'دۆخی داواکاری',
    'header.account': 'هەژمار',
    'common.search': 'گەڕان',
    'app.name': 'کتابخانەی کوردی',
    'home.welcome': 'بەخێربێیت بۆ کتابخانەی کوردی',
    'home.subtitle': 'باشترین فرۆشگای ئۆنلاین بۆ کتابەکانی کوردی',
    'home.featured': 'کتابە تایبەتەکان',
    'home.featuredSubtitle': 'پێشنیارەکانمان بۆ تۆ',
    'home.bestsellers': 'باشترین فرۆشراوەکان',
    'home.bestsellersSubtitle': 'بەناوبانگترین کتێبەکان لای کڕیاران',
    'home.newReleases': 'کتابە نوێکان',
    'home.newReleasesSubtitle': 'نوێترین بڵاوکراوەکان ببینە',
    'home.newReleasesDesc': 'کۆمەڵێک لە نوێترین و باشترین کتێبە کوردییەکان',
    'offers.limitedTime': 'کاتی دیاریکراو',
    'home.viewAll': 'بینینی هەموو',
    'hero.badge': 'کۆمەڵەی نوێ ٢٠٢٥',
    'book.price': 'نرخ',
    'book.by': 'لەلایەن:',
    'book.author': 'نووسەر',
    'book.publisher': 'ناشر:',
    'book.reviews': 'نرخاندن',
    'book.quantity': 'بڕ:',
    'book.pages': 'لاپەڕە:',
    'book.language': 'زمان:',
    'book.publishDate': 'بەرواری بڵاوکردنەوە:',
    'book.description': 'وەسف',
    'book.moreInfo': 'زانیاری زیاتر',
    'book.tags': 'تاگەکان:',
    'book.technicalInfo': 'زانیاری تەکنیکی',
    'book.category': 'پۆل',
    'book.relatedBooks': 'کتابە هاوشێوەکان',
    'book.addToCart': 'زیادکردن بۆ سەبەتە',
    'book.buyNow': 'ئێستا بیکڕە',
    'book.inStock': 'بەردەستە',
    'book.outOfStock': 'ناوبەردەست',
    'cart.title': 'سەبەتەی کڕین',
    'cart.empty': 'سەبەتەکەت بەتاڵە',
    'cart.total': 'کۆی گشتی',
    'cart.checkout': 'تەواوکردنی کڕین',
    'search.title': 'گەڕان',
    'search.placeholder': 'ناوی کتاب، نووسەر یان پۆل بنووسە...',
    'search.noResults': 'هیچ کتابێک نەدۆزرایەوە',
    'search.filters': 'فیلتەرەکان',
    'search.sortBy': 'ریزکردن بەپێی:',
    'search.newest': 'نوێترین',
    'search.oldest': 'کۆنترین',
    'search.nameAZ': 'ناو (ئ - ی)',
    'search.nameZA': 'ناو (ی - ئ)',
    'search.priceLowHigh': 'نرخ نزم بۆ بەرز',
    'search.priceHighLow': 'نرخ بەرز بۆ نزم',
    'search.mostPopular': 'باشترین',
    'search.allCategories': 'هەموو پۆلەکان',
    'search.priceRange': 'ناوچەی نرخ',
    'search.minPrice': 'کەمترین نرخ',
    'search.maxPrice': 'زۆرترین نرخ',
    'search.applyFilter': 'بەکارهێنان',
    'search.showAll': 'پیشاندانی هەموو',
    'search.resultsFound': 'ئەنجام دۆزرایەوە',
    'authors.title': 'نووسەران',
    'authors.biography': 'ژیاننامە',
    'authors.viewProfile': 'بینینی پرۆفایڵ',
    'auth.login': 'ژوورەوە',
    'auth.register': 'خۆناوکردن',
    'auth.email': 'ئیمێڵ',
    'auth.password': 'زِروشە',
    'auth.confirmPassword': 'دووبارە زِروشە',
    'auth.name': 'ناو',
    'auth.forgotPassword': 'زِروشەت لەبیرچووە؟',
    'auth.noAccount': 'هەژمارت نیە؟',
    'auth.haveAccount': 'پێشتر خۆت تۆمار کردووە؟',
    'auth.signIn': 'چوونە ژوورەوە',
    'auth.signUp': 'خۆت تۆمار بکە',
    'auth.rememberMe': 'لەبیرم بکه',
    'auth.quickTest': 'تاقیکردنی خێرا',
    'auth.forTesting': 'بۆ تاقیکردنەوە:',
    'auth.emailLabel': 'ئیمەیل:',
    'auth.passwordLabel': 'پاسۆرد:',
    'auth.error.invalidCredentials': 'ئیمەیل یان پاسۆرد هەڵەیە',
    'auth.error.emailUsed': 'ئەم ئیمەیلە پێشتر بەکارهاتووە',
    'auth.createAccount': 'هەژمارێکی نوێ دروست بکە',
    'auth.orLogin': 'یان بچۆ ژوورەوە',
    'auth.firstName': 'ناوی یەکەم',
    'auth.lastName': 'ناوی دووەم',
    'auth.phone': 'ژمارەی تەلەفۆن',
    'auth.optional': '(ئیختیاری)',
    'auth.chooseStrongPassword': 'پاسۆردێکی بەهێز هەڵبژێرە',
    'auth.minChars': 'لانیکەم ٦ پیت دەبێت',
    'auth.creatingAccount': 'هەژمار دروست بکە',
    'auth.termsAgreement': 'هەژمار دروستکردن واتە ڕازیبوونە بە',
    'auth.terms': 'مەرجەکان',
    'auth.privacyPolicy': 'سیاسەتی تایبەتێتی',
    'auth.and': 'و',
    'book.inCart': 'سەبەت',
    'book.notInCart': 'نییە',
    'profile.dashboard': 'دەشبۆرد',
    'profile.orders': 'داواکاریەکان',
    'profile.wishlist': 'لیستی ویستەکان',
    'profile.addresses': 'ناونیشانەکان',
    'profile.accountDetails': 'وردەکاری هەژمار',
    'profile.logout': 'دەرچوون',
    'profile.personalInfo': 'زانیاری کەسایەتی',
    'profile.updateInfo': 'نوێکردنەوەی زانیاریەکان',
    'profile.save': 'پاشەکەوتکردن',
    'profile.changePassword': 'گۆڕینی زِروشە',
    'profile.orderHistory': 'مێژووی داواکاریەکان',
    'profile.noOrders': 'هیچ داواکارییەکت نیە',
    'profile.orderDetails': 'وردەکاری داواکاری',
    'profile.recentOrders': 'دوایین داواکاریەکان',
    'status.available': 'بەردەستە',
    'status.unavailable': 'ناوبەردەست',
    'status.outOfStock': 'لە کۆمەڵ چووە',
    'form.required': 'وایە',
    'form.invalidEmail': 'ئیمێڵەکە دروست نیە',
    'form.passwordsDontMatch': 'زِروشەکان یەکنین',
    'form.passwordTooShort': 'زِروشە باید لای کەمی ٦ نووسە بێت',
    'common.loading': 'چاوەڕێ بکە...',
    'common.pleaseWait': 'چاوەڕێ بکە...',
    'common.error': 'هەڵەیەک ڕوویدا',
    'common.success': 'سەرکەوتوو بوو',
    'buttons.viewAll': 'بینینی هەموو',
    'buttons.viewAllShort': 'هەمووی',
    'buttons.readMore': 'زیاتر بخوێنەرەوە',
    'buttons.addToCart': 'زیادکردن بۆ سەبەتە',
    'buttons.buyNow': 'ئێستا بیکڕە',
    'buttons.buy': 'کڕین',
    'buttons.save': 'پاشکەوتکردن',
    'buttons.cancel': 'پاشگەزبوونەوە',
    'buttons.edit': 'دەستکاری',
    'buttons.delete': 'سڕینەوە',
    'buttons.confirm': 'پەسەندکردن',
    'buttons.viewDetails': 'بینینی وردەکاری',
    'categories.literature': 'ئەدەبیات',
    'categories.poetry': 'شیعر',
    'categories.history': 'مێژوو',
    'categories.children': 'منداڵان',
    'categories.education': 'پەروەردە',
    'categories.science': 'زانست',
    'categories.religion': 'ئایین',
    'categories.biography': 'ژیاننامە',
    'categories.philosophy': 'فەلسەفە',
    'categories.politics': 'سیاسەت',
    'categories.culture': 'کلتوور',
    'footer.aboutUs': 'دەربارەی ئێمە',
    'footer.contactInfo': 'زانیاری پەیوەندی',
    'footer.followUs': 'شوێنمان بکەوە',
    'footer.copyright': 'مافی چاپ کتابخانەی کوردی. هەموو مافەکان پارێزراون.',
    'sections.featuredBooks': 'کتابە تایبەتەکان',
    'sections.bestSellers': 'باشترین فرۆشراوەکان',
    'sections.newReleases': 'کتابە نوێکان',
    'sections.specialOffers': 'پێشکەشە تایبەتەکان',
    'sections.statistics': 'ئامارەکان',
    'offers.discount': 'داشکاندنی تا ٥٠٪ لەسەر کتابە هەڵبژاردەکان',
    'offers.viewOffers': 'بینینی پێشکەشەکان',
    'stats.books': 'کتاب',
    'stats.authors': 'نووسەر',
    'stats.publishers': 'ناشر',
    // Admin translations
    'admin.login': 'چوونە ژوورەوەی بەڕێوەبەر',
    'admin.username': 'ناوی بەکارهێنەر',
    'admin.password': 'وشەی نهێنی',
    'admin.enterUsername': 'ناوی بەکارهێنەر',
    'admin.enterPassword': 'وشەی نهێنی',
    'admin.loginButton': 'چوونە ژوورەوە',
    'admin.loggingIn': 'چاوەڕوان بە...',
    'admin.invalidCredentials': 'ناوی بەکارهێنەر یان وشەی نهێنی هەڵەیە',
    'admin.accessPanel': 'بۆ دەستڕاگەیشتن بە پانێڵی بەڕێوەبەر',
    'admin.demoCredentials': 'زانیاریەکانی تاقیکردنەوە:',
    'admin.panel': 'پانێڵی بەڕێوەبەر',
    'admin.welcome': 'بەخێربێیت بەڕێوەبەر',
    'admin.logout': 'دەرچوون',
    'admin.dashboard': 'داشبۆرد',
    'admin.manageBooks': 'بەڕێوەبردنی کتابەکان',
    'admin.manageAuthors': 'بەڕێوەبردنی نووسەران',
    'admin.addBook': 'کتابی نوێ',
    'admin.addAuthor': 'نووسەری نوێ',
    'admin.addNewBook': 'کتابی نوێ زیاد بکە',
    'admin.addNewAuthor': 'نووسەری نوێ زیاد بکە',
    'admin.title': 'ناونیشان',
    'admin.author': 'نووسەر',
    'admin.publisher': 'چاپخانە',
    'admin.price': 'نرخ (یۆرۆ)',
    'admin.description': 'وهسف',
    'admin.nameKurdish': 'ناو (کوردی)',
    'admin.nameLatin': 'ناو (لاتینی)',
    'admin.birthYear': 'ساڵی لەدایکبوون',
    'admin.deathYear': 'ساڵی مردن (ئاپشناڵ)',
    'admin.biographyKurdish': 'بیۆگرافی (کوردی)',
    'admin.totalBooks': 'کتابەکان',
    'admin.totalAuthors': 'نووسەران',
    'admin.totalReviews': 'نرخاندنەکان',
    'admin.avgRating': 'ڕێژەی نرخاندن',
    'admin.recentActivity': 'چالاکیە تازەکان',
    'admin.bookAdded': 'کتاب زیادکرا!',
    'admin.authorAdded': 'نووسەر زیادکرا!',
    'admin.actions': 'کردارەکان',
    'admin.rating': 'نرخاندن',
    'admin.books': 'کتاب',
    'stats.customers': 'کڕیار دڵخۆش',
    'description.categories': 'کتابەکان بە پێی بابەت و پۆل دابەش کراون',
    'footer.aboutTitle': 'دەربارەی ئێمە',
    'footer.aboutDescription': 'کتابخانەی کوردی باشترین فرۆشگای ئۆنلاینە بۆ کتابەکانی کوردی',
    'footer.quickLinks': 'بەستەر خێراکان',
    'footer.customerService': 'خزمەتگوزاری کڕیار',
    'footer.contact': 'پەیوەندی',
    'footer.newsletter': 'نیوزلێتەر',
    'footer.newsletterDescription': 'ئاگاداربە لە کتابە نوێکان و پێشکەشە تایبەتەکان',
    'footer.subscribe': 'نووسین',
    'auth.profile': 'پرۆفایل',
    'auth.orders': 'داواکاریەکان',
    'auth.favorites': 'دڵخوازەکان',
    'auth.logout': 'چوونەدەرەوە',
    'cart.itemCount': 'کۆی کتابەکان:',
    'cart.subtotal': 'کۆی نرخ:',
    'cart.shipping': 'گەیاندن:',
    'cart.shippingFree': 'خۆڕایی',
    'cart.continueShopping': 'دەوامی کڕین',
    'cart.emptyMessage': 'هیچ کتابێکت نەخستووەتە ناو سەبەتەکەت',
    'cart.clearCart': 'پاککردنەوەی سەبەتە',
    'cart.orderSummary': 'کورتەی سفارش',
    'cart.freeShipping': 'گەیاندنی خۆڕایی',
    'cart.returns': 'گەڕاندنەوەی ٧ ڕۆژ',
    'cart.buyerProtection': 'پاراستنی کڕیار',
    'cart.remove': 'سڕینەوە',
    'footer.shipping': 'گەیاندن',
    'footer.returns': 'گەڕاندنەوە',
    'footer.faq': 'پرسیارە دووبارەکان',
    'footer.help': 'یارمەتی',
    'footer.emailPlaceholder': 'ئیمەیڵەکەت بنووسە...',
    'footer.privacy': 'سیاسەتی تایبەتێتی',
    'footer.terms': 'مەرجەکانی بەکارهێنان',
    'footer.cookies': 'سیاسەتی کوکیز',
    'books.subtitle': 'گەڕان لە کتابە کوردییەکاندا',
    'books.category': 'پۆل',
    'books.search': 'گەڕان',
    'books.searchPlaceholder': 'گەڕان بە ناو یان نووسەر...',
    'books.sortBy': 'ڕیزکردن بە',
    'books.sortName': 'ناو',
    'books.sortPrice': 'نرخ',
    'books.sortRating': 'هەڵسەنگاندن',
    'books.sortYear': 'ساڵ',
    'books.found': 'دۆزرایەوە:',
    'books.noResults': 'هیچ کتابێک نەدۆزرایەوە',
    'books.noResultsMessage': 'تکایە گەڕانەکەت گۆڕین یان پالاوتنی جیاواز هەڵبژێرە',
    'authors.subtitle': 'ناسین ببە بە نووسەرە بەناوبانگەکانی کوردی',
    'authors.search': 'گەڕان لە نووسەراندا...',
    'authors.sortBy': 'ڕیزبەندی',
    'authors.sortName': 'ناو',
    'authors.sortBooks': 'کتابەکان',
    'authors.sortYear': 'ساڵی لەدایکبوون',
    'authors.found': 'نووسەر دۆزرایەوە',
    'authors.birthYear': 'ساڵی لەدایکبوون:',
    'authors.nationality': 'نەتەوەیی:',
    'authors.noBooks': 'هیچ کتابێک نییە',
    'authors.noAuthorsFound': 'هیچ نووسەرێک نەدۆزرایەوە',
    'authors.popularAuthors': 'نووسەرە بەناوبانگەکان',
    'authors.clearSearch': 'پاککردنەوەی گەڕان',
    'search.noResultsFor': 'هیچ ئەنجامێک نەدۆزرایەوە بۆ',
    'authors.noAuthorsMessage': 'تکایە پەیوەندی جیاواز بەکار بهێنە',
    'authors.book': 'کتاب',
    'authors.books': 'کتاب',
    'authors.moreBooks': 'کتابی تر',
    'status.bestseller': 'باشترین فرۆشراو',
    'status.featured': 'تایبەت',
    'status.newRelease': 'نوێ',
    'status.sale': 'داشکاندن',
    'status.limited': 'سنووردار',
    'categories.all': 'هەموو پۆلەکان'
  },
  en: {
    'site.title': 'Kurdish Library',
    'site.description': 'The best online store for Kurdish books',
    'nav.home': 'Home',
    'nav.categories': 'Categories',
    'nav.books': 'Books',
    'nav.authors': 'Authors',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.cart': 'Cart',
    'nav.wishlist': 'Wishlist',
    'nav.profile': 'Profile',
    'nav.menu': 'Menu',
    'nav.language': 'Language',
    'nav.search': 'Search',
    'nav.login': 'Login',
    'nav.register': 'Register',
    'header.orderStatus': 'Order Status',
    'header.account': 'Account',
    'common.search': 'Search',
    'app.name': 'Kurdish Library',
    'home.welcome': 'Welcome to Kurdish Library',
    'home.subtitle': 'The best online store for Kurdish books',
    'home.featured': 'Featured Books',
    'home.featuredSubtitle': 'Our recommendations for you',
    'home.bestsellers': 'Best Sellers',
    'home.bestsellersSubtitle': 'Most popular books among our customers',
    'home.newReleases': 'New Releases',
    'home.newReleasesSubtitle': 'Check out the latest releases',
    'home.newReleasesDesc': 'A collection of the newest and best Kurdish books',
    'offers.limitedTime': 'Limited Time',
    'home.viewAll': 'View All',
    'hero.badge': 'New Collection 2025',
    'book.price': 'Price',
    'book.by': 'By:',
    'book.author': 'Author',
    'book.publisher': 'Publisher:',
    'book.reviews': 'Reviews',
    'book.quantity': 'Quantity:',
    'book.pages': 'Pages:',
    'book.language': 'Language:',
    'book.publishDate': 'Publication Date:',
    'book.description': 'Description',
    'book.moreInfo': 'More Info',
    'book.tags': 'Tags:',
    'book.technicalInfo': 'Technical Information',
    'book.category': 'Category',
    'book.relatedBooks': 'Related Books',
    'book.addToCart': 'Add to Cart',
    'book.buyNow': 'Buy Now',
    'book.inStock': 'In Stock',
    'book.outOfStock': 'Out of Stock',
    'cart.title': 'Shopping Cart',
    'cart.empty': 'Your cart is empty',
    'cart.total': 'Total',
    'cart.checkout': 'Checkout',
    'search.title': 'Search',
    'search.placeholder': 'Enter book name, author or category...',
    'search.noResults': 'No books found',
    'search.filters': 'Filters',
    'search.sortBy': 'Sort by:',
    'search.newest': 'Newest',
    'search.oldest': 'Oldest',
    'search.nameAZ': 'Name (A-Z)',
    'search.nameZA': 'Name (Z-A)',
    'search.priceLowHigh': 'Price Low to High',
    'search.priceHighLow': 'Price High to Low',
    'search.mostPopular': 'Most Popular',
    'search.allCategories': 'All Categories',
    'search.priceRange': 'Price Range',
    'search.minPrice': 'Minimum Price',
    'search.maxPrice': 'Maximum Price',
    'search.applyFilter': 'Apply Filter',
    'search.showAll': 'Show All',
    'search.resultsFound': 'results found',
    'authors.title': 'Authors',
    'authors.biography': 'Biography',
    'authors.viewProfile': 'View Profile',
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.name': 'Full Name',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.noAccount': "Don't have an account?",
    'auth.haveAccount': 'Already have an account?',
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.rememberMe': 'Remember me',
    'auth.quickTest': 'Quick Test',
    'auth.forTesting': 'For testing:',
    'auth.emailLabel': 'Email:',
    'auth.passwordLabel': 'Password:',
    'auth.error.invalidCredentials': 'Invalid email or password',
    'auth.error.emailUsed': 'This email is already in use',
    'auth.createAccount': 'Create a new account',
    'auth.orLogin': 'or Login',
    'auth.firstName': 'First Name',
    'auth.lastName': 'Last Name',
    'auth.phone': 'Phone Number',
    'auth.optional': '(Optional)',
    'auth.chooseStrongPassword': 'Choose a strong password',
    'auth.minChars': 'Must be at least 6 characters',
    'auth.creatingAccount': 'Create Account',
    'auth.termsAgreement': 'Creating an account means agreeing to',
    'auth.terms': 'Terms',
    'auth.privacyPolicy': 'Privacy Policy',
    'auth.and': 'and',
    'book.inCart': 'In Cart',
    'book.notInCart': 'Not in Cart',
    'profile.dashboard': 'Dashboard',
    'profile.orders': 'Orders',
    'profile.wishlist': 'Wishlist',
    'profile.addresses': 'Addresses',
    'profile.accountDetails': 'Account Details',
    'profile.logout': 'Logout',
    'profile.personalInfo': 'Personal Information',
    'profile.updateInfo': 'Update Information',
    'profile.save': 'Save',
    'profile.changePassword': 'Change Password',
    'profile.orderHistory': 'Order History',
    'profile.noOrders': 'No orders yet',
    'profile.orderDetails': 'Order Details',
    'profile.recentOrders': 'Recent Orders',
    'status.available': 'Available',
    'status.unavailable': 'Unavailable',
    'status.outOfStock': 'Out of Stock',
    'form.required': 'Required',
    'form.invalidEmail': 'Invalid email address',
    'form.passwordsDontMatch': 'Passwords do not match',
    'form.passwordTooShort': 'Password must be at least 6 characters',
    'common.loading': 'Loading...',
    'common.pleaseWait': 'Please wait...',
    'common.error': 'An error occurred',
    'common.success': 'Success',
    'buttons.viewAll': 'View All',
    'buttons.viewAllShort': 'All',
    'buttons.readMore': 'Read More',
    'buttons.addToCart': 'Add to Cart',
    'buttons.buyNow': 'Buy Now',
    'buttons.buy': 'Buy',
    'buttons.save': 'Save',
    'buttons.cancel': 'Cancel',
    'buttons.edit': 'Edit',
    'buttons.delete': 'Delete',
    'buttons.confirm': 'Confirm',
    'buttons.viewDetails': 'View Details',
    'categories.literature': 'Literature',
    'categories.poetry': 'Poetry',
    'categories.history': 'History',
    'categories.children': 'Children',
    'categories.education': 'Education',
    'categories.science': 'Science',
    'categories.religion': 'Religion',
    'categories.biography': 'Biography',
    'categories.philosophy': 'Philosophy',
    'categories.politics': 'Politics',
    'categories.culture': 'Culture',
    'footer.aboutUs': 'About Us',
    'footer.contactInfo': 'Contact Information',
    'footer.followUs': 'Follow Us',
    'footer.copyright': 'Copyright Kurdish Library. All rights reserved.',
    'sections.featuredBooks': 'Featured Books',
    'sections.bestSellers': 'Best Sellers',
    'sections.newReleases': 'New Releases',
    'sections.specialOffers': 'Special Offers',
    'sections.statistics': 'Statistics',
    'offers.discount': 'Up to 50% discount on selected books',
    'offers.viewOffers': 'View Offers',
    'stats.books': 'Books',
    'stats.authors': 'Authors',
    'stats.publishers': 'Publishers',
    // Admin translations
    'admin.login': 'Admin Login',
    'admin.username': 'Username',
    'admin.password': 'Password',
    'admin.enterUsername': 'Enter username',
    'admin.enterPassword': 'Enter password',
    'admin.loginButton': 'Login',
    'admin.loggingIn': 'Logging in...',
    'admin.invalidCredentials': 'Invalid username or password',
    'admin.accessPanel': 'Access the admin panel',
    'admin.demoCredentials': 'Demo Credentials:',
    'admin.panel': 'Admin Panel',
    'admin.welcome': 'Welcome Admin',
    'admin.logout': 'Logout',
    'admin.dashboard': 'Dashboard',
    'admin.manageBooks': 'Manage Books',
    'admin.manageAuthors': 'Manage Authors',
    'admin.addBook': 'Add Book',
    'admin.addAuthor': 'Add Author',
    'admin.addNewBook': 'Add New Book',
    'admin.addNewAuthor': 'Add New Author',
    'admin.title': 'Title',
    'admin.author': 'Author',
    'admin.publisher': 'Publisher',
    'admin.price': 'Price (EUR)',
    'admin.description': 'Description',
    'admin.nameKurdish': 'Name (Kurdish)',
    'admin.nameLatin': 'Name (Latin)',
    'admin.birthYear': 'Birth Year',
    'admin.deathYear': 'Death Year (Optional)',
    'admin.biographyKurdish': 'Biography (Kurdish)',
    'admin.totalBooks': 'Total Books',
    'admin.totalAuthors': 'Authors',
    'admin.totalReviews': 'Reviews',
    'admin.avgRating': 'Avg Rating',
    'admin.recentActivity': 'Recent Activity',
    'admin.bookAdded': 'Book added!',
    'admin.authorAdded': 'Author added!',
    'admin.actions': 'Actions',
    'admin.rating': 'Rating',
    'admin.books': 'books',
    'stats.customers': 'Happy Customers',
    'description.categories': 'Books organized by topics and categories',
    'footer.aboutTitle': 'About Us',
    'footer.aboutDescription': 'Kurdish Library is the best online store for Kurdish books',
    'footer.quickLinks': 'Quick Links',
    'footer.customerService': 'Customer Service',
    'footer.contact': 'Contact',
    'footer.newsletter': 'Newsletter',
    'footer.newsletterDescription': 'Stay updated on new books and special offers',
    'footer.subscribe': 'Subscribe',
    'auth.profile': 'Profile',
    'auth.orders': 'Orders',
    'auth.favorites': 'Favorites',
    'auth.logout': 'Logout',
    'cart.itemCount': 'Items:',
    'cart.subtotal': 'Subtotal:',
    'cart.shipping': 'Shipping:',
    'cart.shippingFree': 'Free',
    'cart.continueShopping': 'Continue Shopping',
    'cart.emptyMessage': 'You haven\'t added any books to your cart yet',
    'cart.clearCart': 'Clear Cart',
    'cart.orderSummary': 'Order Summary',
    'cart.freeShipping': 'Free Shipping',
    'cart.returns': '7-Day Returns',
    'cart.buyerProtection': 'Buyer Protection',
    'cart.remove': 'Remove',
    'footer.shipping': 'Shipping',
    'footer.returns': 'Returns',
    'footer.faq': 'FAQ',
    'footer.help': 'Help',
    'footer.emailPlaceholder': 'Enter your email...',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.cookies': 'Cookie Policy',
    'books.subtitle': 'Discover Kurdish books collection',
    'books.category': 'Category',
    'books.search': 'Search',
    'books.searchPlaceholder': 'Search by title or author...',
    'books.sortBy': 'Sort by',
    'books.sortName': 'Name',
    'books.sortPrice': 'Price',
    'books.sortRating': 'Rating',
    'books.sortYear': 'Year',
    'books.found': 'Found:',
    'books.noResults': 'No books found',
    'books.noResultsMessage': 'Try changing your search terms or filters',
    'authors.subtitle': 'Meet renowned Kurdish authors',
    'authors.search': 'Search authors...',
    'authors.sortBy': 'Sort by',
    'authors.sortName': 'Name',
    'authors.sortBooks': 'Books',
    'authors.sortYear': 'Birth Year',
    'authors.found': 'authors found',
    'authors.birthYear': 'Birth Year:',
    'authors.nationality': 'Nationality:',
    'authors.noBooks': 'No books available',
    'authors.noAuthorsFound': 'No authors found',
    'authors.popularAuthors': 'Popular Authors',
    'authors.clearSearch': 'Clear Search',
    'search.noResultsFor': 'No results found for',
    'authors.noAuthorsMessage': 'Try using different search terms',
    'authors.book': 'book',
    'authors.books': 'books',
    'authors.moreBooks': 'more books',
    'status.bestseller': 'Bestseller',
    'status.featured': 'Featured',
    'status.newRelease': 'New Release',
    'status.sale': 'Sale',
    'status.limited': 'Limited',
    'categories.all': 'All Categories'
  },
  de: {
    'site.title': 'Kurdische Bibliothek',
    'site.description': 'Der beste Online-Shop für kurdische Bücher',
    'nav.home': 'Startseite',
    'nav.categories': 'Kategorien',
    'nav.books': 'Bücher',
    'nav.authors': 'Autoren',
    'nav.about': 'Über uns',
    'nav.contact': 'Kontakt',
    'nav.cart': 'Warenkorb',
    'nav.wishlist': 'Wunschliste',
    'nav.profile': 'Profil',
    'nav.menu': 'Menü',
    'nav.language': 'Sprache',
    'nav.search': 'Suchen',
    'nav.login': 'Anmelden',
    'nav.register': 'Registrieren',
    'header.orderStatus': 'Bestellstatus',
    'header.account': 'Konto',
    'common.search': 'Suchen',
    'app.name': 'Kurdische Bibliothek',
    'home.welcome': 'Willkommen in der Kurdischen Bibliothek',
    'home.subtitle': 'Der beste Online-Shop für kurdische Bücher',
    'home.featured': 'Empfohlene Bücher',
    'home.featuredSubtitle': 'Unsere Empfehlungen für Sie',
    'home.bestsellers': 'Bestseller',
    'home.bestsellersSubtitle': 'Beliebteste Bücher bei unseren Kunden',
    'home.newReleases': 'Neuerscheinungen',
    'home.newReleasesSubtitle': 'Entdecken Sie die neuesten Veröffentlichungen',
    'home.newReleasesDesc': 'Eine Sammlung der neuesten und besten kurdischen Bücher',
    'offers.limitedTime': 'Begrenzte Zeit',
    'home.viewAll': 'Alle anzeigen',
    'hero.badge': 'Neue Kollektion 2025',
    'book.price': 'Preis',
    'book.by': 'Von:',
    'book.author': 'Autor',
    'book.publisher': 'Verlag:',
    'book.reviews': 'Bewertungen',
    'book.quantity': 'Menge:',
    'book.pages': 'Seiten:',
    'book.language': 'Sprache:',
    'book.publishDate': 'Veröffentlichungsdatum:',
    'book.description': 'Beschreibung',
    'book.moreInfo': 'Weitere Informationen',
    'book.tags': 'Tags:',
    'book.technicalInfo': 'Technische Informationen',
    'book.category': 'Kategorie',
    'book.relatedBooks': 'Ähnliche Bücher',
    'book.addToCart': 'In den Warenkorb',
    'book.buyNow': 'Jetzt kaufen',
    'book.inStock': 'Auf Lager',
    'book.outOfStock': 'Nicht auf Lager',
    'cart.title': 'Warenkorb',
    'cart.empty': 'Ihr Warenkorb ist leer',
    'cart.total': 'Gesamt',
    'cart.checkout': 'Zur Kasse',
    'search.title': 'Suchen',
    'search.placeholder': 'Buchname, Autor oder Kategorie eingeben...',
    'search.noResults': 'Keine Bücher gefunden',
    'search.filters': 'Filter',
    'search.sortBy': 'Sortieren nach:',
    'search.newest': 'Neueste',
    'search.oldest': 'Älteste',
    'search.nameAZ': 'Name (A-Z)',
    'search.nameZA': 'Name (Z-A)',
    'search.priceLowHigh': 'Preis niedrig bis hoch',
    'search.priceHighLow': 'Preis hoch bis niedrig',
    'search.mostPopular': 'Am beliebtesten',
    'search.allCategories': 'Alle Kategorien',
    'search.priceRange': 'Preisspanne',
    'search.minPrice': 'Mindestpreis',
    'search.maxPrice': 'Höchstpreis',
    'search.applyFilter': 'Filter anwenden',
    'search.showAll': 'Alle anzeigen',
    'search.resultsFound': 'Ergebnisse gefunden',
    'authors.title': 'Autoren',
    'authors.biography': 'Biografie',
    'authors.viewProfile': 'Profil anzeigen',
    'auth.login': 'Anmelden',
    'auth.register': 'Registrieren',
    'auth.email': 'E-Mail',
    'auth.password': 'Passwort',
    'auth.confirmPassword': 'Passwort bestätigen',
    'auth.name': 'Vollständiger Name',
    'auth.forgotPassword': 'Passwort vergessen?',
    'auth.noAccount': 'Haben Sie noch kein Konto?',
    'auth.haveAccount': 'Haben Sie bereits ein Konto?',
    'auth.signIn': 'Anmelden',
    'auth.signUp': 'Registrieren',
    'auth.rememberMe': 'Angemeldet bleiben',
    'auth.quickTest': 'Schnelltest',
    'auth.forTesting': 'Zum Testen:',
    'auth.emailLabel': 'E-Mail:',
    'auth.passwordLabel': 'Passwort:',
    'auth.error.invalidCredentials': 'Ungültige E-Mail oder Passwort',
    'auth.error.emailUsed': 'Diese E-Mail wird bereits verwendet',
    'auth.createAccount': 'Neues Konto erstellen',
    'auth.orLogin': 'oder Anmelden',
    'auth.firstName': 'Vorname',
    'auth.lastName': 'Nachname',
    'auth.phone': 'Telefonnummer',
    'auth.optional': '(Optional)',
    'auth.chooseStrongPassword': 'Wählen Sie ein starkes Passwort',
    'auth.minChars': 'Muss mindestens 6 Zeichen lang sein',
    'auth.creatingAccount': 'Konto erstellen',
    'auth.termsAgreement': 'Das Erstellen eines Kontos bedeutet die Zustimmung zu',
    'auth.terms': 'Bedingungen',
    'auth.privacyPolicy': 'Datenschutzrichtlinie',
    'auth.and': 'und',
    'book.inCart': 'Im Warenkorb',
    'book.notInCart': 'Nicht im Warenkorb',
    'profile.dashboard': 'Dashboard',
    'profile.orders': 'Bestellungen',
    'profile.wishlist': 'Wunschliste',
    'profile.addresses': 'Adressen',
    'profile.accountDetails': 'Kontodaten',
    'profile.logout': 'Abmelden',
    'profile.personalInfo': 'Persönliche Informationen',
    'profile.updateInfo': 'Informationen aktualisieren',
    'profile.save': 'Speichern',
    'profile.changePassword': 'Passwort ändern',
    'profile.orderHistory': 'Bestellhistorie',
    'profile.noOrders': 'Noch keine Bestellungen',
    'profile.orderDetails': 'Bestelldetails',
    'profile.recentOrders': 'Letzte Bestellungen',
    'status.available': 'Verfügbar',
    'status.unavailable': 'Nicht verfügbar',
    'status.outOfStock': 'Nicht auf Lager',
    'form.required': 'Erforderlich',
    'form.invalidEmail': 'Ungültige E-Mail-Adresse',
    'form.passwordsDontMatch': 'Passwörter stimmen nicht überein',
    'form.passwordTooShort': 'Passwort muss mindestens 6 Zeichen haben',
    'common.loading': 'Lädt...',
    'common.pleaseWait': 'Bitte warten...',
    'common.error': 'Ein Fehler ist aufgetreten',
    'common.success': 'Erfolgreich',
    'buttons.viewAll': 'Alle anzeigen',
    'buttons.viewAllShort': 'Alle',
    'buttons.readMore': 'Mehr lesen',
    'buttons.addToCart': 'In den Warenkorb',
    'buttons.buyNow': 'Jetzt kaufen',
    'buttons.buy': 'Kaufen',
    'buttons.save': 'Speichern',
    'buttons.cancel': 'Abbrechen',
    'buttons.edit': 'Bearbeiten',
    'buttons.delete': 'Löschen',
    'buttons.confirm': 'Bestätigen',
    'buttons.viewDetails': 'Details anzeigen',
    'categories.literature': 'Literatur',
    'categories.poetry': 'Poesie',
    'categories.history': 'Geschichte',
    'categories.children': 'Kinder',
    'categories.education': 'Bildung',
    'categories.science': 'Wissenschaft',
    'categories.religion': 'Religion',
    'categories.biography': 'Biografie',
    'categories.philosophy': 'Philosophie',
    'categories.politics': 'Politik',
    'categories.culture': 'Kultur',
    'footer.aboutUs': 'Über uns',
    'footer.contactInfo': 'Kontaktinformationen',
    'footer.followUs': 'Folgen Sie uns',
    'footer.copyright': 'Copyright Kurdische Bibliothek. Alle Rechte vorbehalten.',
    'sections.featuredBooks': 'Empfohlene Bücher',
    'sections.bestSellers': 'Bestseller',
    'sections.newReleases': 'Neuerscheinungen',
    'sections.specialOffers': 'Sonderangebote',
    'sections.statistics': 'Statistiken',
    'offers.discount': 'Bis zu 50% Rabatt auf ausgewählte Bücher',
    'offers.viewOffers': 'Angebote anzeigen',
    'stats.books': 'Bücher',
    'stats.authors': 'Autoren',
    'stats.publishers': 'Verlage',
    // Admin translations
    'admin.login': 'Admin Anmeldung',
    'admin.username': 'Benutzername',
    'admin.password': 'Passwort',
    'admin.enterUsername': 'Benutzername eingeben',
    'admin.enterPassword': 'Passwort eingeben',
    'admin.loginButton': 'Anmelden',
    'admin.loggingIn': 'Anmeldung...',
    'admin.invalidCredentials': 'Ungültiger Benutzername oder Passwort',
    'admin.accessPanel': 'Zugang zum Admin-Panel',
    'admin.demoCredentials': 'Demo Anmeldedaten:',
    'admin.panel': 'Admin Panel',
    'admin.welcome': 'Willkommen Admin',
    'admin.logout': 'Abmelden',
    'admin.dashboard': 'Dashboard',
    'admin.manageBooks': 'Bücher Verwalten',
    'admin.manageAuthors': 'Autoren Verwalten',
    'admin.addBook': 'Buch Hinzufügen',
    'admin.addAuthor': 'Autor Hinzufügen',
    'admin.addNewBook': 'Neues Buch Hinzufügen',
    'admin.addNewAuthor': 'Neuen Autor Hinzufügen',
    'admin.title': 'Titel',
    'admin.author': 'Autor',
    'admin.publisher': 'Verlag',
    'admin.price': 'Preis (EUR)',
    'admin.description': 'Beschreibung',
    'admin.nameKurdish': 'Name (Kurdisch)',
    'admin.nameLatin': 'Name (Lateinisch)',
    'admin.birthYear': 'Geburtsjahr',
    'admin.deathYear': 'Todesjahr (Optional)',
    'admin.biographyKurdish': 'Biografie (Kurdisch)',
    'admin.totalBooks': 'Bücher Gesamt',
    'admin.totalAuthors': 'Autoren',
    'admin.totalReviews': 'Bewertungen',
    'admin.avgRating': 'Durchschnitt',
    'admin.recentActivity': 'Neueste Aktivitäten',
    'admin.bookAdded': 'Buch hinzugefügt!',
    'admin.authorAdded': 'Autor hinzugefügt!',
    'admin.actions': 'Aktionen',
    'admin.rating': 'Bewertung',
    'admin.books': 'Bücher',
    'stats.customers': 'Zufriedene Kunden',
    'description.categories': 'Bücher nach Themen und Kategorien organisiert',
    'footer.aboutTitle': 'Über uns',
    'footer.aboutDescription': 'Kurdische Bibliothek ist der beste Online-Shop für kurdische Bücher',
    'footer.quickLinks': 'Schnelle Links',
    'footer.customerService': 'Kundenservice',
    'footer.contact': 'Kontakt',
    'footer.newsletter': 'Newsletter',
    'footer.newsletterDescription': 'Bleiben Sie über neue Bücher und Sonderangebote informiert',
    'footer.subscribe': 'Abonnieren',
    'auth.profile': 'Profil',
    'auth.orders': 'Bestellungen',
    'auth.favorites': 'Favoriten',
    'auth.logout': 'Abmelden',
    'cart.itemCount': 'Artikel:',
    'cart.subtotal': 'Zwischensumme:',
    'cart.shipping': 'Versand:',
    'cart.shippingFree': 'Kostenlos',
    'cart.continueShopping': 'Weiter einkaufen',
    'cart.emptyMessage': 'Sie haben noch keine Bücher in Ihren Warenkorb gelegt',
    'cart.clearCart': 'Warenkorb leeren',
    'cart.orderSummary': 'Bestellzusammenfassung',
    'cart.freeShipping': 'Kostenloser Versand',
    'cart.returns': '7-Tage Rückgabe',
    'cart.buyerProtection': 'Käuferschutz',
    'cart.remove': 'Entfernen',
    'footer.shipping': 'Versand',
    'footer.returns': 'Rückgabe',
    'footer.faq': 'Häufige Fragen',
    'footer.help': 'Hilfe',
    'footer.emailPlaceholder': 'E-Mail eingeben...',
    'footer.privacy': 'Datenschutz',
    'footer.terms': 'Nutzungsbedingungen',
    'footer.cookies': 'Cookie-Richtlinie',
    'books.subtitle': 'Entdecken Sie kurdische Bücher',
    'books.category': 'Kategorie',
    'books.search': 'Suchen',
    'books.searchPlaceholder': 'Nach Titel oder Autor suchen...',
    'books.sortBy': 'Sortieren nach',
    'books.sortName': 'Name',
    'books.sortPrice': 'Preis',
    'books.sortRating': 'Bewertung',
    'books.sortYear': 'Jahr',
    'books.found': 'Gefunden:',
    'books.noResults': 'Keine Bücher gefunden',
    'books.noResultsMessage': 'Versuchen Sie andere Suchbegriffe oder Filter',
    'authors.subtitle': 'Lernen Sie renommierte kurdische Autoren kennen',
    'authors.search': 'Autoren suchen...',
    'authors.sortBy': 'Sortieren nach',
    'authors.sortName': 'Name',
    'authors.sortBooks': 'Bücher',
    'authors.sortYear': 'Geburtsjahr',
    'authors.found': 'Autoren gefunden',
    'authors.birthYear': 'Geburtsjahr:',
    'authors.nationality': 'Nationalität:',
    'authors.noBooks': 'Keine Bücher verfügbar',
    'authors.noAuthorsFound': 'Keine Autoren gefunden',
    'authors.popularAuthors': 'Beliebte Autoren',
    'authors.clearSearch': 'Suche löschen',
    'search.noResultsFor': 'Keine Ergebnisse gefunden für',
    'authors.noAuthorsMessage': 'Versuchen Sie andere Suchbegriffe',
    'authors.book': 'Buch',
    'authors.books': 'Bücher',
    'authors.moreBooks': 'weitere Bücher',
    'status.bestseller': 'Bestseller',
    'status.featured': 'Empfohlen',
    'status.newRelease': 'Neuerscheinung',
    'status.sale': 'Angebot',
    'status.limited': 'Begrenzt',
    'categories.all': 'Alle Kategorien'
  }
};

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [currentLanguage, setCurrentLanguage] = useState<Language>('ku');

  // Load language from localStorage on component mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && ['ku', 'en', 'de'].includes(savedLanguage)) {
      setCurrentLanguage(savedLanguage);
    }
  }, []);

  // Update html dir and lang attributes when language changes
  useEffect(() => {
    const dir = currentLanguage === 'ku' ? 'rtl' : 'ltr';
    document.documentElement.dir = dir;
    document.documentElement.lang = currentLanguage;
  }, [currentLanguage]);

  const setLanguage = (lang: Language) => {
    setCurrentLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    const langData = (translations as any)[currentLanguage];
    return langData[key] || key;
  };

  const dir = currentLanguage === 'ku' ? 'rtl' : 'ltr';
  const isRTL = dir === 'rtl';

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, t, dir, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};